GATE = "./internal/buildgate/... ./cmd/versioncheck/..."
SD = "./internal/statedigest/... ./internal/frontend/..."
SDRAFT = "./internal/statedigest/... ./internal/frontend/... ./internal/raft/..."
FE_PKG = "./internal/frontend/..."
DEFAULT_PKG = GATE

BG = "internal/buildgate/buildgate.go"
EV = "internal/buildgate/evidence.go"
VD = "internal/statedigest/verdict.go"
DG = "internal/statedigest/digest.go"
FE = "internal/frontend/statedigest.go"

MUTATIONS = [
    ("BG Compare: drop the empty-on-disk branch",
     BG, "\tcase onDisk == \"\":\n\t\treturn Unobserved\n", "", GATE),
    ("BG Compare: drop the empty-running branch",
     BG, "\tcase running == \"\":\n\t\treturn Unobserved\n", "", GATE),
    ("BG Compare: invert the difference test",
     EV, "\tcase running != onDisk:\n\t\treturn RunningStale\n",
     "\tcase running == onDisk:\n\t\treturn RunningStale\n", GATE),
    ("BG Compare: stop downgrading a dirty pair",
     EV, "\tcase buildinfo.IsDirtyID(onDisk):\n\t\treturn DirtyIDMatch\n", "", GATE),
    ("BG Status.Confirms: confirm anything not down",
     BG, "func (s Status) Confirms() bool { return s == TookEffect }",
     "func (s Status) Confirms() bool { return s != NotRunning }", GATE),
    ("BG Status.Confirms: confirm everything",
     BG, "func (s Status) Confirms() bool { return s == TookEffect }",
     "func (s Status) Confirms() bool { return true }", GATE),
    ("BG Status.Stops: drop the unobserved stop",
     BG, "func (v Verdict) Stops() bool { return v == Mismatch || v == Unobserved }",
     "func (v Verdict) Stops() bool { return v == Mismatch }", GATE),
    ("BG Status.Stops: stop on everything",
     BG, "func (v Verdict) Stops() bool { return v == Mismatch || v == Unobserved }",
     "func (v Verdict) Stops() bool { return true }", GATE),
    ("BG Service.Confirms: confirm unconditionally",
     BG, "func (s Service) Confirms() bool { return s.Status.Confirms() }",
     "func (s Service) Confirms() bool { return true }", GATE),
    ("BG Report.Confirmed: skip the per-service check",
     BG, "\t\tif !service.Status.Confirms() {\n\t\t\treturn false\n\t\t}",
     "\t\tif false {\n\t\t\treturn false\n\t\t}", GATE),
    ("BG Report.Confirmed: only a stale daemon stops",
     BG, "\t\tif !service.Status.Confirms() {\n\t\t\treturn false\n\t\t}",
     "\t\tif service.Status == RunningStale {\n\t\t\treturn false\n\t\t}", GATE),
    ("BG Report.Confirmed: an empty report is confirmed",
     BG, "\tif len(r.Services) == 0 {", "\tif false {", GATE),
    ("BG Report.FirstStop: always reports nothing",
     BG, "\tfor _, service := range r.Services {\n\t\tif !service.Status.Confirms() {\n\t\t\treturn service, true\n\t\t}\n\t}",
     "\tfor _, service := range r.Services {\n\t\tif false {\n\t\t\treturn service, true\n\t\t}\n\t}", GATE),
    ("BG check: read the binary last, or never",
     BG, "\tdisk, err := onDiskBuild(paths.binary(name))\n\tif err != nil {",
     "\tdisk, err := \"\", error(nil)\n\tif false {", GATE),
    ("BG check: an unreadable binary is taken as confirmed",
     BG, "\t\treturn unobservedBinary(name, disk, err, paths)",
     "\t\treturn Service{Name: name, Status: TookEffect, OnDisk: disk, Detail: \"assumed fine\"}", GATE),
    ("BG check: a missing log is never not-running",
     BG, "\t\tif os.IsNotExist(err) {", "\t\tif false {", GATE),
    ("BG check: only a stale daemon is not-running",
     BG, "\t\t\t\tStatus:      NotRunning,", "\t\t\t\tStatus:      RunningStale,", GATE),
    ("BG check: a pre-stamping log is unobserved for a different reason",
     BG, "\t\tservice.Reason = ReasonLogPredatesStamping",
     "\t\tservice.Reason = ReasonLogUnreadable", GATE),
    ("BG check: a missing binary is a different reason",
     BG, "\t\tservice.Reason = ReasonBinaryMissing", "\t\tservice.Reason = ReasonBinaryUnreadable", GATE),
    ("BG check: a -dirty pair is reported as took-effect",
     BG, "\tcase DirtyIDMatch:", "\tcase TookEffect:", GATE),
    ("EV runningBuild: never record a build id",
     EV, "\t\tif m := buildLine.FindStringSubmatch(line); m != nil {\n\t\t\tlast = m[1]\n\t\t}",
     "\t\tif m := buildLine.FindStringSubmatch(line); m != nil {\n\t\t\tlast = \"\"\n\t\t}", GATE),
    ("EV runningBuild: drop the service-name filter",
     EV, "\t\tif !strings.Contains(line, prog+\":\") || !strings.Contains(line, \"listening on\") {\n\t\t\tcontinue\n\t\t}",
     "\t\tif !strings.Contains(line, \"listening on\") {\n\t\t\tcontinue\n\t\t}", GATE),
    ("EV runningBuild: keep the FIRST line, not the last",
     EV, "\t\tif m := buildLine.FindStringSubmatch(line); m != nil {\n\t\t\tlast = m[1]\n\t\t}",
     "\t\tif m := buildLine.FindStringSubmatch(line); m != nil {\n\t\t\tif last == \"\" {\n\t\t\t\tlast = m[1]\n\t\t\t}\n\t\t}", GATE),
    ("EV runningBuild: back to bufio's default buffer",
     EV, "\tsc.Buffer(make([]byte, 0, 64*1024), 1024*1024)", "", GATE),
    ("EV onDiskBuild: treat build=unknown as a real id",
     EV, "\t\tif m[1] == unstampedID {", "\t\tif false {", GATE),
    ("EV onDiskBuild: ignore the output, trust the exit status",
     EV, "\tif m := buildLine.FindStringSubmatch(out); m != nil {\n\t\tif m[1] == unstampedID {",
     "\tif m := buildLine.FindStringSubmatch(\"\"); m != nil {\n\t\tif m[1] == unstampedID {", GATE),
    ("EV isUndefinedFlagText: match nothing",
     EV, "func isUndefinedFlagText(out string) bool {\n\treturn strings.Contains(out, \"flag provided but not defined\") ||\n\t\tstrings.Contains(out, \"not defined: -version\")\n}",
     "func isUndefinedFlagText(out string) bool {\n\treturn false\n}", GATE),
    ("EV isUndefinedFlagText: match anything",
     EV, "func isUndefinedFlagText(out string) bool {\n\treturn strings.Contains(out, \"flag provided but not defined\") ||\n\t\tstrings.Contains(out, \"not defined: -version\")\n}",
     "func isUndefinedFlagText(out string) bool {\n\treturn true\n}", GATE),
    ("VD Verdicts: treat one observation as agreement",
     VD, "\tcase len(observed) == 1:\n", "\tcase false:\n", SDRAFT),
    ("VD Verdicts: drop the one-observation rewrite",
     VD, "\tif len(observed) < 2 {", "\tif false {", SDRAFT),
    ("VD Verdicts: call the zero-observation case a match",
     VD, "\t\tcolony.Verdict = Unobserved\n\tcase len(observed) == 1:",
     "\t\tcolony.Verdict = Match\n\tcase len(observed) == 1:", SDRAFT),
    ("VD uniformity: ignore the applied index",
     VD, "\t\tif observation.AppliedIndex != first.AppliedIndex {\n\t\t\tuniformIndex = false\n\t\t}",
     "", SDRAFT),
    ("VD Verdicts: call a moving sample proven divergence",
     VD, "\t\tcase !uniformIndex:\n\t\t\tcolony.Verdict = Unsettled",
     "\t\tcase false:\n\t\t\tcolony.Verdict = Unsettled", SDRAFT),
    ("VD Verdicts: call proven divergence unsettled",
     VD, "\t\tdefault:\n\t\t\tcolony.Verdict = Mismatch\n\t\t\tcolony.Detail = \"all \"",
     "\t\tdefault:\n\t\t\tcolony.Verdict = Unsettled\n\t\t\tcolony.Detail = \"all \"", SDRAFT),
    ("VD Verdicts: never reach the match branch",
     VD, "\t\tcase uniform:\n", "\t\tcase false:\n", SDRAFT),
    ("VD Verdicts: call every colony a mismatch",
     VD, "\t\tcase uniform:\n\t\t\tcolony.Verdict, colony.Agreed = Match, true",
     "\t\tcase uniform:\n\t\t\tcolony.Verdict, colony.Agreed = Mismatch, false", SDRAFT),
    ("VD nodeVerdictFor: report every row as agreeing",
     VD, "\tview.Verdict = Mismatch\n\tview.Detail = \"this Comb's FSM state digest matches \"",
     "\tview.Verdict = Match\n\tview.Detail = \"this Comb's FSM state digest matches \"", SDRAFT),
    ("VD nodeVerdictFor: count no disagreeing peers",
     VD, "\t\tif other.Digest == observation.Digest {\n\t\t\tagreeing++\n\t\t} else {\n\t\t\tothers++\n\t\t}",
     "\t\tif other.Digest == observation.Digest || true {\n\t\t\tagreeing++\n\t\t} else {\n\t\t\tothers++\n\t\t}", SDRAFT),
    ("VD exclusionSuffix: never say a Comb was excluded",
     VD, "\tif observed >= total {\n\t\treturn \"\"\n\t}", "\tif true {\n\t\treturn \"\"\n\t}", SDRAFT),
    ("VD UnobservedNode: lose the index beside a real digest",
     VD, "\t\tAppliedIndex: observation.AppliedIndex,\n\t\tTotal:        total,",
     "\t\tTotal: total,", SDRAFT),
    ("VD UnobservedNode: drop the 'nothing to compare it with' wording",
     VD, "\tif observation.Digest != \"\" {", "\tif false {", SDRAFT),
    ("VD Verdicts.Permits: permit anything but unobserved",
     VD, "func (v Verdict) Permits() bool { return v == Match }",
     "func (v Verdict) Permits() bool { return v != Unobserved }", SDRAFT),
    ("DG Of: let last_index back into the digest",
     DG, "\t\tif fd.Name() == lastIndexFieldName {\n\t\t\tcontinue\n\t\t}", "", SDRAFT),
    ("DG canonicalMessage: replace the map buffer instead of appending",
     DG, "\t\t\tout = append(out, canonicalMap(mmap, fd)...)", "\t\t\tout = canonicalMap(mmap, fd)", SDRAFT),
    ("DG canonicalMap: emit entries in hash order",
     DG, "\tsort.Slice(entries, func(i, j int) bool { return entries[i].sortKey < entries[j].sortKey })",
     "\tsort.Slice(entries, func(i, j int) bool { return i < j })", SDRAFT),
    ("DG appendCanonicalValue: call Bytes() on a string field",
     DG, "\t\tstr := v.String()", "\t\tstr := string(v.Bytes())", SDRAFT),
    ("DG Of: return empty for a nil state",
     DG, "\tvar buf []byte\n\tif state != nil {\n\t\tbuf = canonicalMessage(state.ProtoReflect())\n\t}\n\tsum := sha256.Sum256(buf)",
     "\tvar buf []byte\n\tif state == nil {\n\t\treturn \"\"\n\t}\n\tsum := sha256.Sum256(buf)", SDRAFT),
    ("FE nodeBadgeClass: render a mismatch as ready",
     FE, "\tcase statedigest.Mismatch:\n\t\treturn badgeError", "\tcase statedigest.Mismatch:\n\t\treturn badgeReady", FE_PKG),
    ("FE nodeBadgeClass: render unobserved as ready",
     FE, "\tcase statedigest.Unobserved:\n\t\treturn badgeUnknown", "\tcase statedigest.Unobserved:\n\t\treturn badgeReady", FE_PKG),
    ("FE colonyBadgeClass: render a match as unknown",
     FE, "\tcase statedigest.Match:\n\t\treturn badgeReady\n\tcase statedigest.Mismatch:\n\t\treturn badgeError",
     "\tcase statedigest.Match:\n\t\treturn badgeUnknown\n\tcase statedigest.Mismatch:\n\t\treturn badgeError", FE_PKG),
    ("FE stateDigestRow: reword the row's own verdict",
     FE, "\t\tState:        string(verdict.Verdict),", "\t\tState:        \"state-ok\",", FE_PKG),
]
