"""Mutation manifest for the buildid-gate branch.

Every entry is (label, path, old, new, packages-to-run). The harness
verifies that `old` appears EXACTLY ONCE in `path` before applying
anything, and reports an anchor miss as its own outcome - because a
mutation that was never applied proves nothing and reporting it as a
survivor, or quietly dropping it, is the failure mode this file exists
to prevent.

Paths are written out in full rather than as variables, so a mis-pointed
anchor is visible in review.
"""

GATE = "./internal/buildgate/... ./cmd/versioncheck/..."
SD = "./internal/statedigest/... ./internal/frontend/... ./internal/raft/..."
FE = "./internal/frontend/..."

BG = "internal/buildgate/buildgate.go"
EV = "internal/buildgate/evidence.go"
VD = "internal/statedigest/verdict.go"
DG = "internal/statedigest/digest.go"
FR = "internal/frontend/statedigest.go"

MUTATIONS = [
    # --- Compare: the verdict table -------------------------------------
    ("Compare: drop the empty-on-disk branch",
     EV, '\tcase onDisk == "":\n\t\treturn Unobserved\n', "", GATE),
    ("Compare: drop the empty-running branch",
     EV, '\tcase running == "":\n\t\treturn Unobserved\n', "", GATE),
    ("Compare: invert the difference test",
     EV, "\tcase running != onDisk:\n\t\treturn RunningStale\n",
     "\tcase running == onDisk:\n\t\treturn RunningStale\n", GATE),
    ("Compare: stop downgrading a dirty pair",
     EV, "\tcase buildinfo.IsDirtyID(onDisk):", "\tcase buildinfo.IsDirtyID(onDisk) && false:", GATE),

    # --- the two policy predicates --------------------------------------
    ("Status.Confirms: confirm anything not down",
     BG, "func (s Status) Confirms() bool { return s == TookEffect }",
     "func (s Status) Confirms() bool { return s != NotRunning }", GATE),
    ("Status.Confirms: confirm everything",
     BG, "func (s Status) Confirms() bool { return s == TookEffect }",
     "func (s Status) Confirms() bool { return true }", GATE),
    ("Verdict.Permits: permit anything but unobserved",
     VD, "func (v Verdict) Permits() bool { return v == Match }",
     "func (v Verdict) Permits() bool { return v != Unobserved }", SD),
    ("Verdict.Permits: permit everything",
     VD, "func (v Verdict) Permits() bool { return v == Match }",
     "func (v Verdict) Permits() bool { return true }", SD),
    ("Verdict.Stops: drop the unobserved stop",
     VD, "func (v Verdict) Stops() bool { return v == Mismatch || v == Unobserved }",
     "func (v Verdict) Stops() bool { return v == Mismatch }", SD),
    ("Verdict.Stops: stop on everything",
     VD, "func (v Verdict) Stops() bool { return v == Mismatch || v == Unobserved }",
     "func (v Verdict) Stops() bool { return true }", SD),
    ("Verdict.Stops: stop on nothing",
     VD, "func (v Verdict) Stops() bool { return v == Mismatch || v == Unobserved }",
     "func (v Verdict) Stops() bool { return false }", SD),
    ("Service.Confirms: confirm unconditionally",
     BG, "func (s Service) Confirms() bool { return s.Status.Confirms() }",
     "func (s Service) Confirms() bool { return true }", GATE),

    # --- Report: the Comb-level answer ----------------------------------
    ("Report.Confirmed: skip the per-service check",
     BG, "\tfor _, service := range r.Services {\n\t\tif !service.Status.Confirms() {\n\t\t\treturn false",
     "\tfor _, service := range r.Services {\n\t\tif !service.Status.Confirms() && false {\n\t\t\treturn false", GATE),
    ("Report.Confirmed: only a stale daemon stops",
     BG, "\tfor _, service := range r.Services {\n\t\tif !service.Status.Confirms() {\n\t\t\treturn false",
     "\tfor _, service := range r.Services {\n\t\tif service.Status == RunningStale {\n\t\t\treturn false", GATE),
    ("Report.Confirmed: an empty report is confirmed",
     BG, "\tif len(r.Services) == 0 {", "\tif false {", GATE),
    ("Report.FirstStop: always reports nothing",
     BG, "\t\tif !service.Status.Confirms() {\n\t\t\treturn service, true\n\t\t}",
     "\t\tif !service.Status.Confirms() && false {\n\t\t\treturn service, true\n\t\t}", GATE),
    ("Report.Stops: report nothing",
     BG, "\t\tif !service.Status.Confirms() {\n\t\t\tstops = append(stops, service)\n\t\t}",
     "\t\tif !service.Status.Confirms() && false {\n\t\t\tstops = append(stops, service)\n\t\t}", GATE),

    # --- check: the two independent reads --------------------------------
    ("check: never read the binary on disk",
     BG, "\tdisk, err := onDiskBuild(paths.binary(name))\n\tif err != nil {",
     "\tdisk, err := \"\", error(nil)\n\tif false {", GATE),
    ("check: an unreadable binary is taken as confirmed",
     BG, "\t\treturn unobservedBinary(name, disk, err, paths)",
     '\t\treturn Service{Name: name, Status: TookEffect, OnDisk: disk, Detail: "assumed fine"}', GATE),
    ("check: a missing log is never not-running",
     BG, "\t\tif errors.Is(err, fs.ErrNotExist) {", "\t\tif false {", GATE),
    ("check: a not-running daemon is reported as stale",
     BG, "\t\t\t\tStatus:      NotRunning,", "\t\t\t\tStatus:      RunningStale,", GATE),
    ("check: a pre-stamping log gets a different reason",
     BG, "\t\tservice.Reason = ReasonLogPredatesStamping",
     "\t\tservice.Reason = ReasonLogUnreadable", GATE),
    ("check: a missing binary gets a different reason",
     BG, "\t\tservice.Reason = ReasonBinaryMissing",
     "\t\tservice.Reason = ReasonBinaryUnreadable", GATE),
    ("check: a missing log gets the wrong reason",
     BG, "\t\t\t\tReason:      ReasonLogMissing,", "\t\t\t\tReason:      ReasonLogUnreadable,", GATE),
    ("check: a -dirty pair is reported as took-effect",
     BG, "\tstatus := Compare(disk, run)",
     "\tstatus := Compare(disk, run)\n\tif status == DirtyIDMatch {\n\t\tstatus = TookEffect\n\t}", GATE),
    ("check: drop the evidence from a stale row",
     BG, '\t\tservice.Detail = name + " is running an older build than the binary on disk; " + summary(run, disk) +',
     '\t\tservice.Detail = name + " is running an older build than the binary on disk; " + summary("", "") +', GATE),
    ("check: drop the 'restart it' advice from a stale row",
     BG, '" - the process predates this file, so it was installed but not restarted"',
     '" - the process predates this file"', GATE),
    ("check: swap the running and on-disk ids in the evidence",
     BG, '\treturn "(running " + orNone(running) + ", on disk " + orNone(onDisk) + ")"',
     '\treturn "(running " + orNone(onDisk) + ", on disk " + orNone(running) + ")"', GATE),

    # --- the evidence readers --------------------------------------------
    ("runningBuild: never record a build id",
     EV, "\t\tif m := buildLine.FindStringSubmatch(line); m != nil {\n\t\t\tlast = m[1]\n\t\t}",
     '\t\tif m := buildLine.FindStringSubmatch(line); m != nil {\n\t\t\tlast = ""\n\t\t}', GATE),
    ("runningBuild: drop the service-name filter",
     EV, '\t\tif !strings.Contains(line, prog+":") || !strings.Contains(line, "listening on") {',
     '\t\tif !strings.Contains(line, "listening on") {', GATE),
    ("runningBuild: keep the FIRST line, not the last",
     EV, "\t\tif m := buildLine.FindStringSubmatch(line); m != nil {\n\t\t\tlast = m[1]\n\t\t}",
     "\t\tif m := buildLine.FindStringSubmatch(line); m != nil {\n\t\t\tif last == \"\" {\n\t\t\t\tlast = m[1]\n\t\t\t}\n\t\t}", GATE),
    ("runningBuild: back to bufio's default buffer",
     EV, "\tsc.Buffer(make([]byte, 0, 64*1024), 1024*1024)", "", GATE),
    ("runningBuild: a missing log is a clean read",
     EV, "\treturn last, sc.Err()", "\treturn last, nil", GATE),
    ("onDiskBuild: treat build=unknown as a real id",
     EV, "\t\tif m[1] == unstampedID {", "\t\tif false {", GATE),
    ("onDiskBuild: ignore the output, trust the exit status",
     EV, '\tif m := buildLine.FindStringSubmatch(out); m != nil {',
     '\tif m := buildLine.FindStringSubmatch(""); m != nil {', GATE),
    ("onDiskBuild: a clean run with no id is a read failure",
     EV, '\treturn "", errNoBuildID', '\treturn "", errUndefinedFlag', GATE),
    ("isUndefinedFlagText: match nothing",
     EV, 'func isUndefinedFlagText(out string) bool {\n\treturn strings.Contains(out, "flag provided but not defined") ||\n\t\tstrings.Contains(out, "not defined: -version")\n}',
     "func isUndefinedFlagText(out string) bool {\n\treturn false\n}", GATE),
    ("isUndefinedFlagText: match anything",
     EV, 'func isUndefinedFlagText(out string) bool {\n\treturn strings.Contains(out, "flag provided but not defined") ||\n\t\tstrings.Contains(out, "not defined: -version")\n}',
     "func isUndefinedFlagText(out string) bool {\n\treturn true\n}", GATE),

    # --- statedigest: the four verdicts -----------------------------------
    ("Verdicts: treat one observation as agreement",
     VD, "\tcase len(observed) == 1:\n", "\tcase false:\n", SD),
    ("Verdicts: drop the one-observation rewrite",
     VD, "\tif len(observed) < 2 {", "\tif false {", SD),
    ("Verdicts: call the zero-observation case a match",
     VD, "\t\tcolony.Verdict = Unobserved\n\tcase len(observed) == 1:",
     "\t\tcolony.Verdict = Match\n\tcase len(observed) == 1:", SD),
    ("uniformity: ignore the applied index",
     VD, "\t\tif observation.AppliedIndex != first.AppliedIndex {\n\t\t\tuniformIndex = false\n\t\t}",
     "", SD),
    ("Verdicts: call a moving sample proven divergence",
     VD, "\t\tcase !uniformIndex:", "\t\tcase !uniformIndex && false:", SD),
    ("Verdicts: call proven divergence unsettled",
     VD, '\t\tdefault:\n\t\t\tcolony.Verdict = Mismatch\n\t\t\tcolony.Detail = "all "',
     '\t\tdefault:\n\t\t\tcolony.Verdict = Unsettled\n\t\t\tcolony.Detail = "all "', SD),
    ("Verdicts: never reach the match branch",
     VD, "\t\tcase uniform:\n", "\t\tcase uniform && false:\n", SD),
    ("Verdicts: call every colony a mismatch",
     VD, "\t\t\tcolony.Verdict, colony.Agreed = Match, true",
     "\t\t\tcolony.Verdict, colony.Agreed = Mismatch, false", SD),
    ("Verdicts: agreed without two observations",
     VD, "\t\tcolony.Verdict, colony.Agreed = Match, true",
     "\t\tcolony.Verdict, colony.Agreed = Match, len(observed) == 1", SD),
    ("nodeVerdictFor: report every row as agreeing",
     VD, '\tview.Verdict = Mismatch\n\tview.Detail = "this Comb\'s FSM state digest matches "',
     '\tview.Verdict = Match\n\tview.Detail = "this Comb\'s FSM state digest matches "', SD),
    ("nodeVerdictFor: count no disagreeing peers",
     VD, "\t\tif other.Digest == observation.Digest {\n\t\t\tagreeing++\n\t\t} else {\n\t\t\tothers++\n\t\t}",
     "\t\tif other.Digest == observation.Digest || true {\n\t\t\tagreeing++\n\t\t} else {\n\t\t\tothers++\n\t\t}", SD),
    ("nodeVerdictFor: drop the 'cannot say which side is wrong' disclaimer",
     VD, '" - the state machines have diverged, and the digest does not say which side is wrong"',
     '" - the state machines have diverged"', SD),
    ("exclusionSuffix: never say a Comb was excluded",
     VD, "\tif observed >= total {\n\t\treturn \"\"\n\t}", "\tif true {\n\t\treturn \"\"\n\t}", SD),
    ("UnobservedNode: lose the index beside a real digest",
     VD, "\t\tAppliedIndex: observation.AppliedIndex,\n\t\tTotal:        total,",
     "\t\tTotal: total,", SD),
    ("UnobservedNode: drop the 'nothing to compare it with' wording",
     VD, '\tif observation.Digest != "" {', "\tif false {", SD),
    ("UnobservedNode: claim an unread digest was read",
     VD, '"this Comb\'s FSM state digest could not be read, so it is excluded from the colony-wide "',
     '"this Comb reported an FSM state digest that was excluded from the colony-wide "', SD),

    # --- statedigest: the canonical encoding -------------------------------
    ("Of: let last_index back into the digest",
     DG, '\t\tif fd.Name() == lastIndexFieldName {\n\t\t\tcontinue\n\t\t}', "", SD),
    ("canonicalMessage: replace the map buffer instead of appending",
     DG, "\t\t\tout = append(out, canonicalMap(mmap, fd)...)", "\t\t\tout = canonicalMap(mmap, fd)", SD),
    ("canonicalMessage: emit fields in declaration order, not field order [KNOWN-REDUNDANT]",
     DG, "\tsort.Slice(descs, func(i, j int) bool { return descs[i].Number() < descs[j].Number() })",
     "\tsort.Slice(descs, func(i, j int) bool { return i < j })", SD),
    ("canonicalMap: emit entries in hash order",
     DG, "\tsort.Slice(entries, func(i, j int) bool { return entries[i].sortKey < entries[j].sortKey })",
     "\tsort.Slice(entries, func(i, j int) bool { return i < j })", SD),
    ("appendCanonicalValue: call Bytes() on a string field",
     DG, "\t\tstr := v.String()", "\t\tstr := string(v.Bytes())", SD),
    ("canonSingularKind: stop distinguishing string from bytes",
     DG, "\tcase protoreflect.StringKind, protoreflect.BytesKind:\n\t\treturn canonKindBytes",
     "\tcase protoreflect.StringKind, protoreflect.BytesKind:\n\t\treturn canonKindFixed", SD),
    ("canonFixedBits: compare floats by value, not by bits",
     DG, "\tcase protoreflect.FloatKind:\n\t\treturn uint64(math.Float32bits(float32(v.Float())))",
     "\tcase protoreflect.FloatKind:\n\t\treturn uint64(v.Float())", SD),
    ("Of: return empty for a nil state",
     DG, "\tvar buf []byte\n\tif state != nil {\n\t\tbuf = canonicalMessage(state.ProtoReflect())\n\t}\n\tsum := sha256.Sum256(buf)",
     "\tvar buf []byte\n\tif state == nil {\n\t\treturn \"\"\n\t}\n\tsum := sha256.Sum256(buf)", SD),

    # --- frontend: the presentation split ---------------------------------
    ("nodeBadgeClass: render a mismatch as ready",
     FR, "func nodeBadgeClass(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn badgeReady\n\tcase statedigest.Mismatch:\n\t\treturn badgeError",
     "func nodeBadgeClass(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn badgeReady\n\tcase statedigest.Mismatch:\n\t\treturn badgeReady", FE),
    ("nodeBadgeClass: render unsettled as ready",
     FR, "func nodeBadgeClass(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn badgeReady\n\tcase statedigest.Mismatch:\n\t\treturn badgeError\n\tcase statedigest.Unsettled:\n\t\treturn badgeDegraded",
     "func nodeBadgeClass(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn badgeReady\n\tcase statedigest.Mismatch:\n\t\treturn badgeError\n\tcase statedigest.Unsettled:\n\t\treturn badgeReady", FE),
    ("colonyBadgeClass: render a match as unknown",
     FR, "func colonyBadgeClass(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn badgeReady",
     "func colonyBadgeClass(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn badgeUnknown", FE),
    ("colonyBadgeClass: render unsettled as ready",
     FR, "func colonyBadgeClass(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn badgeReady\n\tcase statedigest.Mismatch:\n\t\treturn badgeError\n\tcase statedigest.Unsettled:\n\t\treturn badgeDegraded",
     "func colonyBadgeClass(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn badgeReady\n\tcase statedigest.Mismatch:\n\t\treturn badgeError\n\tcase statedigest.Unsettled:\n\t\treturn badgeReady", FE),
    ("nodeBadgeLabel: call a mismatch 'State matches'",
     FR, 'func nodeBadgeLabel(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn "State matches"\n\tcase statedigest.Mismatch:\n\t\treturn "State differs"',
     'func nodeBadgeLabel(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn "State matches"\n\tcase statedigest.Mismatch:\n\t\treturn "State matches"', FE),
    ("colonyBadgeLabel: call a diverged colony 'State agreed'",
     FR, 'func colonyBadgeLabel(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn colonyAgreedLabel\n\tcase statedigest.Mismatch:\n\t\treturn colonyDivergedLabel',
     'func colonyBadgeLabel(verdict statedigest.Verdict) string {\n\tswitch verdict {\n\tcase statedigest.Match:\n\t\treturn colonyAgreedLabel\n\tcase statedigest.Mismatch:\n\t\treturn colonyAgreedLabel', FE),
    ("stateDigestRow: reword the row's own verdict",
     FR, "\t\tState:        string(verdict.Verdict),", '\t\tState:        "state-ok",', FE),
    ("stateDigestRow: carry a blank badge class",
     FR, "\t\tBadgeClass:   nodeBadgeClass(verdict.Verdict),",
     '\t\tBadgeClass:   "",', FE),
    ("stateDigestVerdicts: drop the colony detail",
     FR, "\t\tDetail:     colonyVerdict.Detail,", '\t\tDetail:     "",', FE),
]
