// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/rpc/manager.proto

package rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerService_Status_FullMethodName        = "/apiary.rpc.v1.ManagerService/Status"
	ManagerService_CreateVM_FullMethodName      = "/apiary.rpc.v1.ManagerService/CreateVM"
	ManagerService_UpdateVM_FullMethodName      = "/apiary.rpc.v1.ManagerService/UpdateVM"
	ManagerService_DeleteVM_FullMethodName      = "/apiary.rpc.v1.ManagerService/DeleteVM"
	ManagerService_ForcePurgeVM_FullMethodName  = "/apiary.rpc.v1.ManagerService/ForcePurgeVM"
	ManagerService_GetVM_FullMethodName         = "/apiary.rpc.v1.ManagerService/GetVM"
	ManagerService_ListVMs_FullMethodName       = "/apiary.rpc.v1.ManagerService/ListVMs"
	ManagerService_UploadISO_FullMethodName     = "/apiary.rpc.v1.ManagerService/UploadISO"
	ManagerService_ListISOs_FullMethodName      = "/apiary.rpc.v1.ManagerService/ListISOs"
	ManagerService_DeleteISO_FullMethodName     = "/apiary.rpc.v1.ManagerService/DeleteISO"
	ManagerService_HostStats_FullMethodName     = "/apiary.rpc.v1.ManagerService/HostStats"
	ManagerService_GetVMConsole_FullMethodName  = "/apiary.rpc.v1.ManagerService/GetVMConsole"
	ManagerService_CreateNetwork_FullMethodName = "/apiary.rpc.v1.ManagerService/CreateNetwork"
	ManagerService_ListNetworks_FullMethodName  = "/apiary.rpc.v1.ManagerService/ListNetworks"
	ManagerService_DeleteNetwork_FullMethodName = "/apiary.rpc.v1.ManagerService/DeleteNetwork"
	ManagerService_CreateAPIKey_FullMethodName  = "/apiary.rpc.v1.ManagerService/CreateAPIKey"
	ManagerService_ListAPIKeys_FullMethodName   = "/apiary.rpc.v1.ManagerService/ListAPIKeys"
	ManagerService_RevokeAPIKey_FullMethodName  = "/apiary.rpc.v1.ManagerService/RevokeAPIKey"
)

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagerService is the external RPC API exposed by managerd.
// CreateVM/UpdateVM/DeleteVM record ephemeral VM definitions via raftd -
// there is still no bhyve/jail/zfs backend, so nothing actually runs a VM
// yet, but the definitions are real, replicated, and persisted.
type ManagerServiceClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	UpdateVM(ctx context.Context, in *UpdateVMRequest, opts ...grpc.CallOption) (*UpdateVMResponse, error)
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error)
	// ForcePurgeVM is an escape hatch for a VM tombstoned by DeleteVM
	// whose owning node will never reconcile it away (permanently
	// offline/decommissioned) - see CLAUDE.md's "What's not implemented
	// yet" note on resource reclaim. It only succeeds against a VM
	// already in VM_STATE_DELETING (call DeleteVM first) and removes the
	// record outright, the same way the owning node's own reconciler
	// would via PurgeVM - but it does NOT touch that node's real ZFS
	// dataset or bhyve VM, since (by definition, this being needed at
	// all) that node can't be reached. Use only when the owning node is
	// confirmed gone for good; otherwise its resources are silently
	// orphaned with no record left to indicate they exist.
	ForcePurgeVM(ctx context.Context, in *ForcePurgeVMRequest, opts ...grpc.CallOption) (*ForcePurgeVMResponse, error)
	// GetVM and ListVMs only succeed against the current leader - see
	// api/internalpb/raftd.proto's GetVM/ListVMs doc comments for why v1's
	// read consistency model is deliberately as simple as its write model.
	GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error)
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	// UploadISO, ListISOs, and DeleteISO manage installer images stored
	// locally on *this* managerd's own node - unlike VM definitions,
	// these are physical data (see CLAUDE.md's physical/ephemeral
	// distinction) and are never replicated through raft. UploadISO is
	// client-streaming so a large image doesn't have to fit in one
	// message; see ADR-0017 for why verification happens server-side
	// rather than trusting a client-computed hash.
	UploadISO(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadISORequest, UploadISOResponse], error)
	ListISOs(ctx context.Context, in *ListISOsRequest, opts ...grpc.CallOption) (*ListISOsResponse, error)
	DeleteISO(ctx context.Context, in *DeleteISORequest, opts ...grpc.CallOption) (*DeleteISOResponse, error)
	// HostStats reports a point-in-time snapshot of *this* node's own
	// resource usage and hardware health - physical, per-node data like
	// ISOs above, gathered locally by managerd (see internal/hoststats),
	// never routed through raft.
	HostStats(ctx context.Context, in *HostStatsRequest, opts ...grpc.CallOption) (*HostStatsResponse, error)
	// GetVMConsole reports how to reach a running VM's VNC framebuffer,
	// for the web UI's noVNC-based console page (ADR-0020). Like HostStats,
	// this only answers for a VM actually running on *this* node - see
	// GetVMConsoleResponse's doc comment for the v1 limitation that
	// follows from that.
	GetVMConsole(ctx context.Context, in *GetVMConsoleRequest, opts ...grpc.CallOption) (*GetVMConsoleResponse, error)
	// CreateNetwork/ListNetworks/DeleteNetwork manage NetworkDefinitions -
	// VLAN/subnet/bridge segments a VM can attach to (see ADR-0022).
	// CreateNetwork/DeleteNetwork just submit a Command through raft
	// (like CreateVM/DeleteVM); ListNetworks reads current state, subject
	// to the same leader-only requirement as ListVMs.
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error)
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error)
	// CreateAPIKey/ListAPIKeys/RevokeAPIKey manage credentials for this
	// service's own RPC surface (ADR-0023). CreateAPIKey is the only
	// place a raw key is ever returned - it cannot be retrieved again
	// after this response. Once at least one key exists, every RPC on
	// this service (including these three) requires a valid one; before
	// that, everything remains open, matching this project's behavior
	// today.
	CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error)
	ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error)
	RevokeAPIKey(ctx context.Context, in *RevokeAPIKeyRequest, opts ...grpc.CallOption) (*RevokeAPIKeyResponse, error)
}

type managerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerServiceClient(cc grpc.ClientConnInterface) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ManagerService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) UpdateVM(ctx context.Context, in *UpdateVMRequest, opts ...grpc.CallOption) (*UpdateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_UpdateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ForcePurgeVM(ctx context.Context, in *ForcePurgeVMRequest, opts ...grpc.CallOption) (*ForcePurgeVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForcePurgeVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_ForcePurgeVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) UploadISO(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadISORequest, UploadISOResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagerService_ServiceDesc.Streams[0], ManagerService_UploadISO_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadISORequest, UploadISOResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerService_UploadISOClient = grpc.ClientStreamingClient[UploadISORequest, UploadISOResponse]

func (c *managerServiceClient) ListISOs(ctx context.Context, in *ListISOsRequest, opts ...grpc.CallOption) (*ListISOsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListISOsResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListISOs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DeleteISO(ctx context.Context, in *DeleteISORequest, opts ...grpc.CallOption) (*DeleteISOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteISOResponse)
	err := c.cc.Invoke(ctx, ManagerService_DeleteISO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) HostStats(ctx context.Context, in *HostStatsRequest, opts ...grpc.CallOption) (*HostStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostStatsResponse)
	err := c.cc.Invoke(ctx, ManagerService_HostStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetVMConsole(ctx context.Context, in *GetVMConsoleRequest, opts ...grpc.CallOption) (*GetVMConsoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMConsoleResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetVMConsole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNetworkResponse)
	err := c.cc.Invoke(ctx, ManagerService_CreateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNetworkResponse)
	err := c.cc.Invoke(ctx, ManagerService_DeleteNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIKeyResponse)
	err := c.cc.Invoke(ctx, ManagerService_CreateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIKeysResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) RevokeAPIKey(ctx context.Context, in *RevokeAPIKeyRequest, opts ...grpc.CallOption) (*RevokeAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAPIKeyResponse)
	err := c.cc.Invoke(ctx, ManagerService_RevokeAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
// All implementations must embed UnimplementedManagerServiceServer
// for forward compatibility.
//
// ManagerService is the external RPC API exposed by managerd.
// CreateVM/UpdateVM/DeleteVM record ephemeral VM definitions via raftd -
// there is still no bhyve/jail/zfs backend, so nothing actually runs a VM
// yet, but the definitions are real, replicated, and persisted.
type ManagerServiceServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error)
	UpdateVM(context.Context, *UpdateVMRequest) (*UpdateVMResponse, error)
	DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error)
	// ForcePurgeVM is an escape hatch for a VM tombstoned by DeleteVM
	// whose owning node will never reconcile it away (permanently
	// offline/decommissioned) - see CLAUDE.md's "What's not implemented
	// yet" note on resource reclaim. It only succeeds against a VM
	// already in VM_STATE_DELETING (call DeleteVM first) and removes the
	// record outright, the same way the owning node's own reconciler
	// would via PurgeVM - but it does NOT touch that node's real ZFS
	// dataset or bhyve VM, since (by definition, this being needed at
	// all) that node can't be reached. Use only when the owning node is
	// confirmed gone for good; otherwise its resources are silently
	// orphaned with no record left to indicate they exist.
	ForcePurgeVM(context.Context, *ForcePurgeVMRequest) (*ForcePurgeVMResponse, error)
	// GetVM and ListVMs only succeed against the current leader - see
	// api/internalpb/raftd.proto's GetVM/ListVMs doc comments for why v1's
	// read consistency model is deliberately as simple as its write model.
	GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error)
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	// UploadISO, ListISOs, and DeleteISO manage installer images stored
	// locally on *this* managerd's own node - unlike VM definitions,
	// these are physical data (see CLAUDE.md's physical/ephemeral
	// distinction) and are never replicated through raft. UploadISO is
	// client-streaming so a large image doesn't have to fit in one
	// message; see ADR-0017 for why verification happens server-side
	// rather than trusting a client-computed hash.
	UploadISO(grpc.ClientStreamingServer[UploadISORequest, UploadISOResponse]) error
	ListISOs(context.Context, *ListISOsRequest) (*ListISOsResponse, error)
	DeleteISO(context.Context, *DeleteISORequest) (*DeleteISOResponse, error)
	// HostStats reports a point-in-time snapshot of *this* node's own
	// resource usage and hardware health - physical, per-node data like
	// ISOs above, gathered locally by managerd (see internal/hoststats),
	// never routed through raft.
	HostStats(context.Context, *HostStatsRequest) (*HostStatsResponse, error)
	// GetVMConsole reports how to reach a running VM's VNC framebuffer,
	// for the web UI's noVNC-based console page (ADR-0020). Like HostStats,
	// this only answers for a VM actually running on *this* node - see
	// GetVMConsoleResponse's doc comment for the v1 limitation that
	// follows from that.
	GetVMConsole(context.Context, *GetVMConsoleRequest) (*GetVMConsoleResponse, error)
	// CreateNetwork/ListNetworks/DeleteNetwork manage NetworkDefinitions -
	// VLAN/subnet/bridge segments a VM can attach to (see ADR-0022).
	// CreateNetwork/DeleteNetwork just submit a Command through raft
	// (like CreateVM/DeleteVM); ListNetworks reads current state, subject
	// to the same leader-only requirement as ListVMs.
	CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error)
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error)
	// CreateAPIKey/ListAPIKeys/RevokeAPIKey manage credentials for this
	// service's own RPC surface (ADR-0023). CreateAPIKey is the only
	// place a raw key is ever returned - it cannot be retrieved again
	// after this response. Once at least one key exists, every RPC on
	// this service (including these three) requires a valid one; before
	// that, everything remains open, matching this project's behavior
	// today.
	CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error)
	ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error)
	RevokeAPIKey(context.Context, *RevokeAPIKeyRequest) (*RevokeAPIKeyResponse, error)
	mustEmbedUnimplementedManagerServiceServer()
}

// UnimplementedManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerServiceServer struct{}

func (UnimplementedManagerServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedManagerServiceServer) CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedManagerServiceServer) UpdateVM(context.Context, *UpdateVMRequest) (*UpdateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVM not implemented")
}
func (UnimplementedManagerServiceServer) DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedManagerServiceServer) ForcePurgeVM(context.Context, *ForcePurgeVMRequest) (*ForcePurgeVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForcePurgeVM not implemented")
}
func (UnimplementedManagerServiceServer) GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVM not implemented")
}
func (UnimplementedManagerServiceServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedManagerServiceServer) UploadISO(grpc.ClientStreamingServer[UploadISORequest, UploadISOResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadISO not implemented")
}
func (UnimplementedManagerServiceServer) ListISOs(context.Context, *ListISOsRequest) (*ListISOsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListISOs not implemented")
}
func (UnimplementedManagerServiceServer) DeleteISO(context.Context, *DeleteISORequest) (*DeleteISOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteISO not implemented")
}
func (UnimplementedManagerServiceServer) HostStats(context.Context, *HostStatsRequest) (*HostStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HostStats not implemented")
}
func (UnimplementedManagerServiceServer) GetVMConsole(context.Context, *GetVMConsoleRequest) (*GetVMConsoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMConsole not implemented")
}
func (UnimplementedManagerServiceServer) CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedManagerServiceServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedManagerServiceServer) DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNetwork not implemented")
}
func (UnimplementedManagerServiceServer) CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAPIKey not implemented")
}
func (UnimplementedManagerServiceServer) ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAPIKeys not implemented")
}
func (UnimplementedManagerServiceServer) RevokeAPIKey(context.Context, *RevokeAPIKeyRequest) (*RevokeAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAPIKey not implemented")
}
func (UnimplementedManagerServiceServer) mustEmbedUnimplementedManagerServiceServer() {}
func (UnimplementedManagerServiceServer) testEmbeddedByValue()                        {}

// UnsafeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServiceServer will
// result in compilation errors.
type UnsafeManagerServiceServer interface {
	mustEmbedUnimplementedManagerServiceServer()
}

func RegisterManagerServiceServer(s grpc.ServiceRegistrar, srv ManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerService_ServiceDesc, srv)
}

func _ManagerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_UpdateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).UpdateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_UpdateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).UpdateVM(ctx, req.(*UpdateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ForcePurgeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForcePurgeVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ForcePurgeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ForcePurgeVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ForcePurgeVM(ctx, req.(*ForcePurgeVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetVM(ctx, req.(*GetVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_UploadISO_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagerServiceServer).UploadISO(&grpc.GenericServerStream[UploadISORequest, UploadISOResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerService_UploadISOServer = grpc.ClientStreamingServer[UploadISORequest, UploadISOResponse]

func _ManagerService_ListISOs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListISOsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListISOs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListISOs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListISOs(ctx, req.(*ListISOsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DeleteISO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteISORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DeleteISO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_DeleteISO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DeleteISO(ctx, req.(*DeleteISORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_HostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).HostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_HostStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).HostStats(ctx, req.(*HostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetVMConsole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMConsoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetVMConsole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetVMConsole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetVMConsole(ctx, req.(*GetVMConsoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CreateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_DeleteNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CreateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CreateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CreateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CreateAPIKey(ctx, req.(*CreateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListAPIKeys(ctx, req.(*ListAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_RevokeAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).RevokeAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_RevokeAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).RevokeAPIKey(ctx, req.(*RevokeAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerService_ServiceDesc is the grpc.ServiceDesc for ManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apiary.rpc.v1.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ManagerService_Status_Handler,
		},
		{
			MethodName: "CreateVM",
			Handler:    _ManagerService_CreateVM_Handler,
		},
		{
			MethodName: "UpdateVM",
			Handler:    _ManagerService_UpdateVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _ManagerService_DeleteVM_Handler,
		},
		{
			MethodName: "ForcePurgeVM",
			Handler:    _ManagerService_ForcePurgeVM_Handler,
		},
		{
			MethodName: "GetVM",
			Handler:    _ManagerService_GetVM_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _ManagerService_ListVMs_Handler,
		},
		{
			MethodName: "ListISOs",
			Handler:    _ManagerService_ListISOs_Handler,
		},
		{
			MethodName: "DeleteISO",
			Handler:    _ManagerService_DeleteISO_Handler,
		},
		{
			MethodName: "HostStats",
			Handler:    _ManagerService_HostStats_Handler,
		},
		{
			MethodName: "GetVMConsole",
			Handler:    _ManagerService_GetVMConsole_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _ManagerService_CreateNetwork_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _ManagerService_ListNetworks_Handler,
		},
		{
			MethodName: "DeleteNetwork",
			Handler:    _ManagerService_DeleteNetwork_Handler,
		},
		{
			MethodName: "CreateAPIKey",
			Handler:    _ManagerService_CreateAPIKey_Handler,
		},
		{
			MethodName: "ListAPIKeys",
			Handler:    _ManagerService_ListAPIKeys_Handler,
		},
		{
			MethodName: "RevokeAPIKey",
			Handler:    _ManagerService_RevokeAPIKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadISO",
			Handler:       _ManagerService_UploadISO_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/rpc/manager.proto",
}
