// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/rpc/manager.proto

package rpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerService_Status_FullMethodName                      = "/apiary.rpc.v1.ManagerService/Status"
	ManagerService_CreateVM_FullMethodName                    = "/apiary.rpc.v1.ManagerService/CreateVM"
	ManagerService_UpdateVM_FullMethodName                    = "/apiary.rpc.v1.ManagerService/UpdateVM"
	ManagerService_DeleteVM_FullMethodName                    = "/apiary.rpc.v1.ManagerService/DeleteVM"
	ManagerService_ForcePurgeVM_FullMethodName                = "/apiary.rpc.v1.ManagerService/ForcePurgeVM"
	ManagerService_MigrateVM_FullMethodName                   = "/apiary.rpc.v1.ManagerService/MigrateVM"
	ManagerService_SetVMFirewallPaused_FullMethodName         = "/apiary.rpc.v1.ManagerService/SetVMFirewallPaused"
	ManagerService_GetVM_FullMethodName                       = "/apiary.rpc.v1.ManagerService/GetVM"
	ManagerService_ListVMs_FullMethodName                     = "/apiary.rpc.v1.ManagerService/ListVMs"
	ManagerService_UploadISO_FullMethodName                   = "/apiary.rpc.v1.ManagerService/UploadISO"
	ManagerService_ListISOs_FullMethodName                    = "/apiary.rpc.v1.ManagerService/ListISOs"
	ManagerService_DeleteISO_FullMethodName                   = "/apiary.rpc.v1.ManagerService/DeleteISO"
	ManagerService_HostStats_FullMethodName                   = "/apiary.rpc.v1.ManagerService/HostStats"
	ManagerService_GetVMConsole_FullMethodName                = "/apiary.rpc.v1.ManagerService/GetVMConsole"
	ManagerService_GetVMSerialLog_FullMethodName              = "/apiary.rpc.v1.ManagerService/GetVMSerialLog"
	ManagerService_GetNodeConfig_FullMethodName               = "/apiary.rpc.v1.ManagerService/GetNodeConfig"
	ManagerService_UpdateNodeConfig_FullMethodName            = "/apiary.rpc.v1.ManagerService/UpdateNodeConfig"
	ManagerService_SetDatasetQuota_FullMethodName             = "/apiary.rpc.v1.ManagerService/SetDatasetQuota"
	ManagerService_CreateNetwork_FullMethodName               = "/apiary.rpc.v1.ManagerService/CreateNetwork"
	ManagerService_ListNetworks_FullMethodName                = "/apiary.rpc.v1.ManagerService/ListNetworks"
	ManagerService_DeleteNetwork_FullMethodName               = "/apiary.rpc.v1.ManagerService/DeleteNetwork"
	ManagerService_CreateAPIKey_FullMethodName                = "/apiary.rpc.v1.ManagerService/CreateAPIKey"
	ManagerService_ListAPIKeys_FullMethodName                 = "/apiary.rpc.v1.ManagerService/ListAPIKeys"
	ManagerService_RevokeAPIKey_FullMethodName                = "/apiary.rpc.v1.ManagerService/RevokeAPIKey"
	ManagerService_CreateJail_FullMethodName                  = "/apiary.rpc.v1.ManagerService/CreateJail"
	ManagerService_UpdateJail_FullMethodName                  = "/apiary.rpc.v1.ManagerService/UpdateJail"
	ManagerService_DeleteJail_FullMethodName                  = "/apiary.rpc.v1.ManagerService/DeleteJail"
	ManagerService_GetJail_FullMethodName                     = "/apiary.rpc.v1.ManagerService/GetJail"
	ManagerService_ListJails_FullMethodName                   = "/apiary.rpc.v1.ManagerService/ListJails"
	ManagerService_ForcePurgeJail_FullMethodName              = "/apiary.rpc.v1.ManagerService/ForcePurgeJail"
	ManagerService_SimulateNodeFailure_FullMethodName         = "/apiary.rpc.v1.ManagerService/SimulateNodeFailure"
	ManagerService_SimulateNetworkFailure_FullMethodName      = "/apiary.rpc.v1.ManagerService/SimulateNetworkFailure"
	ManagerService_TraceCellPath_FullMethodName               = "/apiary.rpc.v1.ManagerService/TraceCellPath"
	ManagerService_MigrateJail_FullMethodName                 = "/apiary.rpc.v1.ManagerService/MigrateJail"
	ManagerService_ReportVMPhase_FullMethodName               = "/apiary.rpc.v1.ManagerService/ReportVMPhase"
	ManagerService_ReportVMTeardownComplete_FullMethodName    = "/apiary.rpc.v1.ManagerService/ReportVMTeardownComplete"
	ManagerService_ReportJailPhase_FullMethodName             = "/apiary.rpc.v1.ManagerService/ReportJailPhase"
	ManagerService_ReportJailTeardownComplete_FullMethodName  = "/apiary.rpc.v1.ManagerService/ReportJailTeardownComplete"
	ManagerService_PushISOTo_FullMethodName                   = "/apiary.rpc.v1.ManagerService/PushISOTo"
	ManagerService_GetLocalNetworkBridgeStatus_FullMethodName = "/apiary.rpc.v1.ManagerService/GetLocalNetworkBridgeStatus"
	ManagerService_ListAssumptionResults_FullMethodName       = "/apiary.rpc.v1.ManagerService/ListAssumptionResults"
)

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagerService is the external RPC API exposed by managerd.
// CreateVM/UpdateVM/DeleteVM record ephemeral VM definitions via raftd -
// there is still no bhyve/jail/zfs backend, so nothing actually runs a VM
// yet, but the definitions are real, replicated, and persisted.
type ManagerServiceClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	UpdateVM(ctx context.Context, in *UpdateVMRequest, opts ...grpc.CallOption) (*UpdateVMResponse, error)
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error)
	// ForcePurgeVM is an escape hatch for a VM tombstoned by DeleteVM
	// whose owning node will never reconcile it away (permanently
	// offline/decommissioned) - see CLAUDE.md's "What's not implemented
	// yet" note on resource reclaim. It only succeeds against a VM
	// already in VM_STATE_DELETING (call DeleteVM first) and removes the
	// record outright, the same way the owning node's own reconciler
	// would via PurgeVM - but it does NOT touch that node's real ZFS
	// dataset or bhyve VM, since (by definition, this being needed at
	// all) that node can't be reached. Use only when the owning node is
	// confirmed gone for good; otherwise its resources are silently
	// orphaned with no record left to indicate they exist.
	ForcePurgeVM(ctx context.Context, in *ForcePurgeVMRequest, opts ...grpc.CallOption) (*ForcePurgeVMResponse, error)
	// MigrateVM is a manual, explicit, human-triggered operation moving
	// a VM's ownership to target_node_id - Apiary has no automatic
	// scheduling (CLAUDE.md's deliberate stance), so this exists purely
	// to fill the "there's no way to move a VM at all" gap, not to add
	// scheduling logic. It only succeeds when target_node_id is already
	// this VM's replica_node_id - i.e., a HAST secondary already holding
	// a synced copy of the disk (see ADR-0026/ADR-0028) - since for any
	// other target, the VM's disk isn't present there at all: the
	// reconciler would tear down the real disk on the old node
	// (ADR-0025's resource reclaim) and provision a brand-new EMPTY one
	// on the new node, silently destroying the VM's actual data. This
	// isn't a technical limitation to remove later - it's the same
	// "never allow a silently destructive default" caution this
	// project has applied everywhere else. To migrate a VM with no
	// existing replica: set replica_node_id via UpdateVM first, confirm
	// real replication has reached hastctl's own "status: complete" on
	// the target, then call MigrateVM.
	//
	// On success, node_id and replica_node_id are swapped (the old
	// owner becomes the new secondary, continuing replication back) -
	// the reconciler's existing HAST role machinery converges this
	// exactly like any other role change, no new reconciler logic
	// involved.
	MigrateVM(ctx context.Context, in *MigrateVMRequest, opts ...grpc.CallOption) (*MigrateVMResponse, error)
	// SetVMFirewallPaused temporarily suspends enforcement of a VM's
	// firewall_rules (everything allowed) without discarding the
	// configured rule list - useful for troubleshooting connectivity.
	// Deliberately not folded into UpdateVM: UpdateVM replaces a VM's
	// entire record, so a caller toggling just this one field would risk
	// silently wiping firewall_rules/network_id/etc. unless it first
	// fetched and resent the complete current record - see ADR-0049.
	SetVMFirewallPaused(ctx context.Context, in *SetVMFirewallPausedRequest, opts ...grpc.CallOption) (*SetVMFirewallPausedResponse, error)
	// GetVM and ListVMs only succeed against the current leader - see
	// api/internalpb/raftd.proto's GetVM/ListVMs doc comments for why v1's
	// read consistency model is deliberately as simple as its write model.
	GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error)
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	// UploadISO, ListISOs, and DeleteISO manage installer images stored
	// locally on *this* managerd's own node - unlike VM definitions,
	// these are physical data (see CLAUDE.md's physical/ephemeral
	// distinction) and are never replicated through raft. UploadISO is
	// client-streaming so a large image doesn't have to fit in one
	// message; see ADR-0017 for why verification happens server-side
	// rather than trusting a client-computed hash.
	UploadISO(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadISORequest, UploadISOResponse], error)
	ListISOs(ctx context.Context, in *ListISOsRequest, opts ...grpc.CallOption) (*ListISOsResponse, error)
	DeleteISO(ctx context.Context, in *DeleteISORequest, opts ...grpc.CallOption) (*DeleteISOResponse, error)
	// HostStats reports a point-in-time snapshot of *this* node's own
	// resource usage and hardware health - physical, per-node data like
	// ISOs above, gathered locally by managerd (see internal/hoststats),
	// never routed through raft.
	HostStats(ctx context.Context, in *HostStatsRequest, opts ...grpc.CallOption) (*HostStatsResponse, error)
	// GetVMConsole reports how to reach a running VM's VNC framebuffer,
	// for the web UI's noVNC-based console page (ADR-0020). Like HostStats,
	// this only answers for a VM actually running on *this* node - see
	// GetVMConsoleResponse's doc comment for the v1 limitation that
	// follows from that.
	GetVMConsole(ctx context.Context, in *GetVMConsoleRequest, opts ...grpc.CallOption) (*GetVMConsoleResponse, error)
	// GetVMSerialLog returns the tail of a VM's captured serial console
	// log (ADR-0032's EnableSerialLog), for the web UI - previously this
	// required an operator to read the file directly on the owning node.
	// Same locality limitation as GetVMConsole: only answers for a VM
	// confirmed running on *this* node.
	GetVMSerialLog(ctx context.Context, in *GetVMSerialLogRequest, opts ...grpc.CallOption) (*GetVMSerialLogResponse, error)
	// GetNodeConfig/UpdateNodeConfig manage this node's own local runtime
	// settings (currently: the uplink interfaces VLAN tagging/outbound
	// NAT use - see ADR-0048) - physical, per-node data like HostStats/
	// ISOs above, never routed through raft (a NIC name is only ever
	// meaningful to the one node that has it). A change here takes
	// effect the next time this node's managerd restarts, not live -
	// see ADR-0049 for why. See internal/nodeconfig.
	GetNodeConfig(ctx context.Context, in *GetNodeConfigRequest, opts ...grpc.CallOption) (*GetNodeConfigResponse, error)
	UpdateNodeConfig(ctx context.Context, in *UpdateNodeConfigRequest, opts ...grpc.CallOption) (*UpdateNodeConfigResponse, error)
	// SetDatasetQuota sets a ZFS quota on a dataset under this node's own
	// configured Base scope (see internal/zfs.Manager) - physical,
	// per-node storage governance, never routed through raft. See
	// ADR-0049 for the v1 limitation that this can only target a named
	// sub-dataset, not the Base dataset itself.
	SetDatasetQuota(ctx context.Context, in *SetDatasetQuotaRequest, opts ...grpc.CallOption) (*SetDatasetQuotaResponse, error)
	// CreateNetwork/ListNetworks/DeleteNetwork manage NetworkDefinitions -
	// VLAN/subnet/bridge segments a VM can attach to (see ADR-0022).
	// CreateNetwork/DeleteNetwork just submit a Command through raft
	// (like CreateVM/DeleteVM); ListNetworks reads current state, subject
	// to the same leader-only requirement as ListVMs.
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error)
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error)
	// CreateAPIKey/ListAPIKeys/RevokeAPIKey manage credentials for this
	// service's own RPC surface (ADR-0023). CreateAPIKey is the only
	// place a raw key is ever returned - it cannot be retrieved again
	// after this response. Once at least one key exists, every RPC on
	// this service (including these three) requires a valid one; before
	// that, everything remains open, matching this project's behavior
	// today.
	CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error)
	ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error)
	RevokeAPIKey(ctx context.Context, in *RevokeAPIKeyRequest, opts ...grpc.CallOption) (*RevokeAPIKeyResponse, error)
	// CreateJail/UpdateJail/DeleteJail/GetJail/ListJails manage
	// JailDefinitions - see ADR-0026's jail-orchestration half. They
	// mirror the VM RPCs above exactly, including GetJail/ListJails'
	// same leader-only read requirement.
	CreateJail(ctx context.Context, in *CreateJailRequest, opts ...grpc.CallOption) (*CreateJailResponse, error)
	UpdateJail(ctx context.Context, in *UpdateJailRequest, opts ...grpc.CallOption) (*UpdateJailResponse, error)
	DeleteJail(ctx context.Context, in *DeleteJailRequest, opts ...grpc.CallOption) (*DeleteJailResponse, error)
	GetJail(ctx context.Context, in *GetJailRequest, opts ...grpc.CallOption) (*GetJailResponse, error)
	ListJails(ctx context.Context, in *ListJailsRequest, opts ...grpc.CallOption) (*ListJailsResponse, error)
	// ForcePurgeJail mirrors ForcePurgeVM exactly, for a jail tombstoned
	// by DeleteJail whose owning node will never come back to reconcile
	// it away. See ForcePurgeVM's own doc comment above for the full
	// reasoning - it applies identically here.
	ForcePurgeJail(ctx context.Context, in *ForcePurgeJailRequest, opts ...grpc.CallOption) (*ForcePurgeJailResponse, error)
	// SimulateNodeFailure is a read-only "what happens if this node
	// disappears right now" report (ADR-0052, the Dependency Graph
	// Simulator's v1 slice) - not fault injection, nothing is changed.
	// It combines three separate sequential reads (VM list, jail list,
	// raft status) plus live per-remaining-voter reachability checks -
	// not an atomic snapshot; a concurrent cluster change, or a peer
	// becoming reachable/unreachable between checks, could be reflected
	// in one part of the response and not another. Like GetVM/ListVMs,
	// this needs the current leader's own FSM view of VM/jail ownership,
	// so it only succeeds against the current leader; the entire request
	// (not just the failed sub-call) is forwarded on a leader-hint
	// rejection so the report never mixes two different nodes' views.
	// node_id not recognized by raft membership or by any VM/jail's
	// node_id/replica_node_id returns error set, never a misleadingly
	// empty-looking "safe" report.
	SimulateNodeFailure(ctx context.Context, in *SimulateNodeFailureRequest, opts ...grpc.CallOption) (*SimulateNodeFailureResponse, error)
	// SimulateNetworkFailure is the Dependency Graph Simulator's second,
	// read-only slice: which VMs declare an attachment to a managed network if
	// that logical network disappears. It combines separate ListNetworks and
	// ListVMs reads, so it is not an atomic snapshot. The entire request is
	// forwarded on a leader-hint rejection to avoid mixing nodes' FSM views.
	SimulateNetworkFailure(ctx context.Context, in *SimulateNetworkFailureRequest, opts ...grpc.CallOption) (*SimulateNetworkFailureResponse, error)
	// TraceCellPath explains a VM Cell's intended outbound path to one
	// destination (ADR-0058). It is read-only and sends no probe. The
	// trace combines leader-authoritative VM/network intent with bounded
	// observations from the Cell's owner Hive, so results are sequential
	// and non-atomic. The entire request is leader-forwarded if the first
	// authoritative read rejects this node as a follower.
	TraceCellPath(ctx context.Context, in *TraceCellPathRequest, opts ...grpc.CallOption) (*TraceCellPathResponse, error)
	// MigrateJail mirrors MigrateVM exactly, for jails instead of VMs -
	// see MigrateVM's own doc comment above for the full reasoning
	// (including the "target must already be a synced HAST replica"
	// safety requirement), which applies identically here.
	MigrateJail(ctx context.Context, in *MigrateJailRequest, opts ...grpc.CallOption) (*MigrateJailResponse, error)
	// ReportVMPhase/ReportVMTeardownComplete/ReportJailPhase/
	// ReportJailTeardownComplete are peer-to-peer RPCs, not meant for
	// human/API-client use: a reconciler on a node that owns a VM/jail
	// but whose own raftd isn't the current raft leader calls these on
	// the LEADER node's managerd instead, since only the leader's own
	// raftd can ever accept an Apply (ADR-0029) - raftd's internal API
	// stays Unix-socket-only, never exposed over the network; this
	// reuses ManagerService's existing, already-networked, already-
	// optionally-API-key-gated external surface instead of opening a
	// new one. Gated by the same auth as every other RPC here when
	// enabled - see cmd/managerd's -peer-api-key flag.
	ReportVMPhase(ctx context.Context, in *ReportVMPhaseRequest, opts ...grpc.CallOption) (*ReportVMPhaseResponse, error)
	ReportVMTeardownComplete(ctx context.Context, in *ReportVMTeardownCompleteRequest, opts ...grpc.CallOption) (*ReportVMTeardownCompleteResponse, error)
	ReportJailPhase(ctx context.Context, in *ReportJailPhaseRequest, opts ...grpc.CallOption) (*ReportJailPhaseResponse, error)
	ReportJailTeardownComplete(ctx context.Context, in *ReportJailTeardownCompleteRequest, opts ...grpc.CallOption) (*ReportJailTeardownCompleteResponse, error)
	// PushISOTo is the peer-to-peer half of on-demand image fetching
	// (ADR-0041, superseding ADR-0040's browser-triggered ReplicateISO):
	// the *source* node's own managerd calls UploadISO against
	// target_node_id itself, the same way a browser upload would, in
	// response to a peer (usually a reconciler discovering it's missing
	// an ISO/base image a VM names) asking it to push a file it already
	// has. Peer-only, mirrors the Report* RPCs' own reasoning above
	// exactly - never meant for direct human/API-client use.
	PushISOTo(ctx context.Context, in *PushISOToRequest, opts ...grpc.CallOption) (*PushISOToResponse, error)
	// GetLocalNetworkBridgeStatus reports THIS node's own local bridge
	// status for one network - built from RaftClient.ListNetworksLocal
	// (the already-replicated network config, read locally, never leader-
	// restricted) plus the local VLANStatus interface. Deliberately NOT
	// ListNetworks: that RPC is leader-only and forwards to the current
	// leader on a non-leader node, which would silently report the
	// LEADER's bridge state mislabeled as the queried node's own - see
	// ADR-0055 for the live bug this was built to avoid. Never forwards,
	// by construction.
	GetLocalNetworkBridgeStatus(ctx context.Context, in *GetLocalNetworkBridgeStatusRequest, opts ...grpc.CallOption) (*GetLocalNetworkBridgeStatusResponse, error)
	// ListAssumptionResults reports THIS node's own persisted Automated
	// Assumption Checks (ADR-0055) - physical, per-node observational
	// data like HostStats/ISOs above, never routed through raft, and
	// never leader-forwarded (the same locality convention as HostStats).
	// See internal/assumptions/internal/assumecheck.
	ListAssumptionResults(ctx context.Context, in *ListAssumptionResultsRequest, opts ...grpc.CallOption) (*ListAssumptionResultsResponse, error)
}

type managerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerServiceClient(cc grpc.ClientConnInterface) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ManagerService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) UpdateVM(ctx context.Context, in *UpdateVMRequest, opts ...grpc.CallOption) (*UpdateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_UpdateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ForcePurgeVM(ctx context.Context, in *ForcePurgeVMRequest, opts ...grpc.CallOption) (*ForcePurgeVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForcePurgeVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_ForcePurgeVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) MigrateVM(ctx context.Context, in *MigrateVMRequest, opts ...grpc.CallOption) (*MigrateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_MigrateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) SetVMFirewallPaused(ctx context.Context, in *SetVMFirewallPausedRequest, opts ...grpc.CallOption) (*SetVMFirewallPausedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVMFirewallPausedResponse)
	err := c.cc.Invoke(ctx, ManagerService_SetVMFirewallPaused_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) UploadISO(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadISORequest, UploadISOResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagerService_ServiceDesc.Streams[0], ManagerService_UploadISO_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadISORequest, UploadISOResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerService_UploadISOClient = grpc.ClientStreamingClient[UploadISORequest, UploadISOResponse]

func (c *managerServiceClient) ListISOs(ctx context.Context, in *ListISOsRequest, opts ...grpc.CallOption) (*ListISOsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListISOsResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListISOs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DeleteISO(ctx context.Context, in *DeleteISORequest, opts ...grpc.CallOption) (*DeleteISOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteISOResponse)
	err := c.cc.Invoke(ctx, ManagerService_DeleteISO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) HostStats(ctx context.Context, in *HostStatsRequest, opts ...grpc.CallOption) (*HostStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostStatsResponse)
	err := c.cc.Invoke(ctx, ManagerService_HostStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetVMConsole(ctx context.Context, in *GetVMConsoleRequest, opts ...grpc.CallOption) (*GetVMConsoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMConsoleResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetVMConsole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetVMSerialLog(ctx context.Context, in *GetVMSerialLogRequest, opts ...grpc.CallOption) (*GetVMSerialLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMSerialLogResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetVMSerialLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetNodeConfig(ctx context.Context, in *GetNodeConfigRequest, opts ...grpc.CallOption) (*GetNodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeConfigResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetNodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) UpdateNodeConfig(ctx context.Context, in *UpdateNodeConfigRequest, opts ...grpc.CallOption) (*UpdateNodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeConfigResponse)
	err := c.cc.Invoke(ctx, ManagerService_UpdateNodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) SetDatasetQuota(ctx context.Context, in *SetDatasetQuotaRequest, opts ...grpc.CallOption) (*SetDatasetQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDatasetQuotaResponse)
	err := c.cc.Invoke(ctx, ManagerService_SetDatasetQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNetworkResponse)
	err := c.cc.Invoke(ctx, ManagerService_CreateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNetworkResponse)
	err := c.cc.Invoke(ctx, ManagerService_DeleteNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIKeyResponse)
	err := c.cc.Invoke(ctx, ManagerService_CreateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIKeysResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) RevokeAPIKey(ctx context.Context, in *RevokeAPIKeyRequest, opts ...grpc.CallOption) (*RevokeAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAPIKeyResponse)
	err := c.cc.Invoke(ctx, ManagerService_RevokeAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) CreateJail(ctx context.Context, in *CreateJailRequest, opts ...grpc.CallOption) (*CreateJailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJailResponse)
	err := c.cc.Invoke(ctx, ManagerService_CreateJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) UpdateJail(ctx context.Context, in *UpdateJailRequest, opts ...grpc.CallOption) (*UpdateJailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJailResponse)
	err := c.cc.Invoke(ctx, ManagerService_UpdateJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DeleteJail(ctx context.Context, in *DeleteJailRequest, opts ...grpc.CallOption) (*DeleteJailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJailResponse)
	err := c.cc.Invoke(ctx, ManagerService_DeleteJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetJail(ctx context.Context, in *GetJailRequest, opts ...grpc.CallOption) (*GetJailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJailResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListJails(ctx context.Context, in *ListJailsRequest, opts ...grpc.CallOption) (*ListJailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJailsResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListJails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ForcePurgeJail(ctx context.Context, in *ForcePurgeJailRequest, opts ...grpc.CallOption) (*ForcePurgeJailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForcePurgeJailResponse)
	err := c.cc.Invoke(ctx, ManagerService_ForcePurgeJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) SimulateNodeFailure(ctx context.Context, in *SimulateNodeFailureRequest, opts ...grpc.CallOption) (*SimulateNodeFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulateNodeFailureResponse)
	err := c.cc.Invoke(ctx, ManagerService_SimulateNodeFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) SimulateNetworkFailure(ctx context.Context, in *SimulateNetworkFailureRequest, opts ...grpc.CallOption) (*SimulateNetworkFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulateNetworkFailureResponse)
	err := c.cc.Invoke(ctx, ManagerService_SimulateNetworkFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) TraceCellPath(ctx context.Context, in *TraceCellPathRequest, opts ...grpc.CallOption) (*TraceCellPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceCellPathResponse)
	err := c.cc.Invoke(ctx, ManagerService_TraceCellPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) MigrateJail(ctx context.Context, in *MigrateJailRequest, opts ...grpc.CallOption) (*MigrateJailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateJailResponse)
	err := c.cc.Invoke(ctx, ManagerService_MigrateJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ReportVMPhase(ctx context.Context, in *ReportVMPhaseRequest, opts ...grpc.CallOption) (*ReportVMPhaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportVMPhaseResponse)
	err := c.cc.Invoke(ctx, ManagerService_ReportVMPhase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ReportVMTeardownComplete(ctx context.Context, in *ReportVMTeardownCompleteRequest, opts ...grpc.CallOption) (*ReportVMTeardownCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportVMTeardownCompleteResponse)
	err := c.cc.Invoke(ctx, ManagerService_ReportVMTeardownComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ReportJailPhase(ctx context.Context, in *ReportJailPhaseRequest, opts ...grpc.CallOption) (*ReportJailPhaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportJailPhaseResponse)
	err := c.cc.Invoke(ctx, ManagerService_ReportJailPhase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ReportJailTeardownComplete(ctx context.Context, in *ReportJailTeardownCompleteRequest, opts ...grpc.CallOption) (*ReportJailTeardownCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportJailTeardownCompleteResponse)
	err := c.cc.Invoke(ctx, ManagerService_ReportJailTeardownComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) PushISOTo(ctx context.Context, in *PushISOToRequest, opts ...grpc.CallOption) (*PushISOToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushISOToResponse)
	err := c.cc.Invoke(ctx, ManagerService_PushISOTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) GetLocalNetworkBridgeStatus(ctx context.Context, in *GetLocalNetworkBridgeStatusRequest, opts ...grpc.CallOption) (*GetLocalNetworkBridgeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocalNetworkBridgeStatusResponse)
	err := c.cc.Invoke(ctx, ManagerService_GetLocalNetworkBridgeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) ListAssumptionResults(ctx context.Context, in *ListAssumptionResultsRequest, opts ...grpc.CallOption) (*ListAssumptionResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssumptionResultsResponse)
	err := c.cc.Invoke(ctx, ManagerService_ListAssumptionResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServiceServer is the server API for ManagerService service.
// All implementations must embed UnimplementedManagerServiceServer
// for forward compatibility.
//
// ManagerService is the external RPC API exposed by managerd.
// CreateVM/UpdateVM/DeleteVM record ephemeral VM definitions via raftd -
// there is still no bhyve/jail/zfs backend, so nothing actually runs a VM
// yet, but the definitions are real, replicated, and persisted.
type ManagerServiceServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error)
	UpdateVM(context.Context, *UpdateVMRequest) (*UpdateVMResponse, error)
	DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error)
	// ForcePurgeVM is an escape hatch for a VM tombstoned by DeleteVM
	// whose owning node will never reconcile it away (permanently
	// offline/decommissioned) - see CLAUDE.md's "What's not implemented
	// yet" note on resource reclaim. It only succeeds against a VM
	// already in VM_STATE_DELETING (call DeleteVM first) and removes the
	// record outright, the same way the owning node's own reconciler
	// would via PurgeVM - but it does NOT touch that node's real ZFS
	// dataset or bhyve VM, since (by definition, this being needed at
	// all) that node can't be reached. Use only when the owning node is
	// confirmed gone for good; otherwise its resources are silently
	// orphaned with no record left to indicate they exist.
	ForcePurgeVM(context.Context, *ForcePurgeVMRequest) (*ForcePurgeVMResponse, error)
	// MigrateVM is a manual, explicit, human-triggered operation moving
	// a VM's ownership to target_node_id - Apiary has no automatic
	// scheduling (CLAUDE.md's deliberate stance), so this exists purely
	// to fill the "there's no way to move a VM at all" gap, not to add
	// scheduling logic. It only succeeds when target_node_id is already
	// this VM's replica_node_id - i.e., a HAST secondary already holding
	// a synced copy of the disk (see ADR-0026/ADR-0028) - since for any
	// other target, the VM's disk isn't present there at all: the
	// reconciler would tear down the real disk on the old node
	// (ADR-0025's resource reclaim) and provision a brand-new EMPTY one
	// on the new node, silently destroying the VM's actual data. This
	// isn't a technical limitation to remove later - it's the same
	// "never allow a silently destructive default" caution this
	// project has applied everywhere else. To migrate a VM with no
	// existing replica: set replica_node_id via UpdateVM first, confirm
	// real replication has reached hastctl's own "status: complete" on
	// the target, then call MigrateVM.
	//
	// On success, node_id and replica_node_id are swapped (the old
	// owner becomes the new secondary, continuing replication back) -
	// the reconciler's existing HAST role machinery converges this
	// exactly like any other role change, no new reconciler logic
	// involved.
	MigrateVM(context.Context, *MigrateVMRequest) (*MigrateVMResponse, error)
	// SetVMFirewallPaused temporarily suspends enforcement of a VM's
	// firewall_rules (everything allowed) without discarding the
	// configured rule list - useful for troubleshooting connectivity.
	// Deliberately not folded into UpdateVM: UpdateVM replaces a VM's
	// entire record, so a caller toggling just this one field would risk
	// silently wiping firewall_rules/network_id/etc. unless it first
	// fetched and resent the complete current record - see ADR-0049.
	SetVMFirewallPaused(context.Context, *SetVMFirewallPausedRequest) (*SetVMFirewallPausedResponse, error)
	// GetVM and ListVMs only succeed against the current leader - see
	// api/internalpb/raftd.proto's GetVM/ListVMs doc comments for why v1's
	// read consistency model is deliberately as simple as its write model.
	GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error)
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	// UploadISO, ListISOs, and DeleteISO manage installer images stored
	// locally on *this* managerd's own node - unlike VM definitions,
	// these are physical data (see CLAUDE.md's physical/ephemeral
	// distinction) and are never replicated through raft. UploadISO is
	// client-streaming so a large image doesn't have to fit in one
	// message; see ADR-0017 for why verification happens server-side
	// rather than trusting a client-computed hash.
	UploadISO(grpc.ClientStreamingServer[UploadISORequest, UploadISOResponse]) error
	ListISOs(context.Context, *ListISOsRequest) (*ListISOsResponse, error)
	DeleteISO(context.Context, *DeleteISORequest) (*DeleteISOResponse, error)
	// HostStats reports a point-in-time snapshot of *this* node's own
	// resource usage and hardware health - physical, per-node data like
	// ISOs above, gathered locally by managerd (see internal/hoststats),
	// never routed through raft.
	HostStats(context.Context, *HostStatsRequest) (*HostStatsResponse, error)
	// GetVMConsole reports how to reach a running VM's VNC framebuffer,
	// for the web UI's noVNC-based console page (ADR-0020). Like HostStats,
	// this only answers for a VM actually running on *this* node - see
	// GetVMConsoleResponse's doc comment for the v1 limitation that
	// follows from that.
	GetVMConsole(context.Context, *GetVMConsoleRequest) (*GetVMConsoleResponse, error)
	// GetVMSerialLog returns the tail of a VM's captured serial console
	// log (ADR-0032's EnableSerialLog), for the web UI - previously this
	// required an operator to read the file directly on the owning node.
	// Same locality limitation as GetVMConsole: only answers for a VM
	// confirmed running on *this* node.
	GetVMSerialLog(context.Context, *GetVMSerialLogRequest) (*GetVMSerialLogResponse, error)
	// GetNodeConfig/UpdateNodeConfig manage this node's own local runtime
	// settings (currently: the uplink interfaces VLAN tagging/outbound
	// NAT use - see ADR-0048) - physical, per-node data like HostStats/
	// ISOs above, never routed through raft (a NIC name is only ever
	// meaningful to the one node that has it). A change here takes
	// effect the next time this node's managerd restarts, not live -
	// see ADR-0049 for why. See internal/nodeconfig.
	GetNodeConfig(context.Context, *GetNodeConfigRequest) (*GetNodeConfigResponse, error)
	UpdateNodeConfig(context.Context, *UpdateNodeConfigRequest) (*UpdateNodeConfigResponse, error)
	// SetDatasetQuota sets a ZFS quota on a dataset under this node's own
	// configured Base scope (see internal/zfs.Manager) - physical,
	// per-node storage governance, never routed through raft. See
	// ADR-0049 for the v1 limitation that this can only target a named
	// sub-dataset, not the Base dataset itself.
	SetDatasetQuota(context.Context, *SetDatasetQuotaRequest) (*SetDatasetQuotaResponse, error)
	// CreateNetwork/ListNetworks/DeleteNetwork manage NetworkDefinitions -
	// VLAN/subnet/bridge segments a VM can attach to (see ADR-0022).
	// CreateNetwork/DeleteNetwork just submit a Command through raft
	// (like CreateVM/DeleteVM); ListNetworks reads current state, subject
	// to the same leader-only requirement as ListVMs.
	CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error)
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error)
	// CreateAPIKey/ListAPIKeys/RevokeAPIKey manage credentials for this
	// service's own RPC surface (ADR-0023). CreateAPIKey is the only
	// place a raw key is ever returned - it cannot be retrieved again
	// after this response. Once at least one key exists, every RPC on
	// this service (including these three) requires a valid one; before
	// that, everything remains open, matching this project's behavior
	// today.
	CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error)
	ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error)
	RevokeAPIKey(context.Context, *RevokeAPIKeyRequest) (*RevokeAPIKeyResponse, error)
	// CreateJail/UpdateJail/DeleteJail/GetJail/ListJails manage
	// JailDefinitions - see ADR-0026's jail-orchestration half. They
	// mirror the VM RPCs above exactly, including GetJail/ListJails'
	// same leader-only read requirement.
	CreateJail(context.Context, *CreateJailRequest) (*CreateJailResponse, error)
	UpdateJail(context.Context, *UpdateJailRequest) (*UpdateJailResponse, error)
	DeleteJail(context.Context, *DeleteJailRequest) (*DeleteJailResponse, error)
	GetJail(context.Context, *GetJailRequest) (*GetJailResponse, error)
	ListJails(context.Context, *ListJailsRequest) (*ListJailsResponse, error)
	// ForcePurgeJail mirrors ForcePurgeVM exactly, for a jail tombstoned
	// by DeleteJail whose owning node will never come back to reconcile
	// it away. See ForcePurgeVM's own doc comment above for the full
	// reasoning - it applies identically here.
	ForcePurgeJail(context.Context, *ForcePurgeJailRequest) (*ForcePurgeJailResponse, error)
	// SimulateNodeFailure is a read-only "what happens if this node
	// disappears right now" report (ADR-0052, the Dependency Graph
	// Simulator's v1 slice) - not fault injection, nothing is changed.
	// It combines three separate sequential reads (VM list, jail list,
	// raft status) plus live per-remaining-voter reachability checks -
	// not an atomic snapshot; a concurrent cluster change, or a peer
	// becoming reachable/unreachable between checks, could be reflected
	// in one part of the response and not another. Like GetVM/ListVMs,
	// this needs the current leader's own FSM view of VM/jail ownership,
	// so it only succeeds against the current leader; the entire request
	// (not just the failed sub-call) is forwarded on a leader-hint
	// rejection so the report never mixes two different nodes' views.
	// node_id not recognized by raft membership or by any VM/jail's
	// node_id/replica_node_id returns error set, never a misleadingly
	// empty-looking "safe" report.
	SimulateNodeFailure(context.Context, *SimulateNodeFailureRequest) (*SimulateNodeFailureResponse, error)
	// SimulateNetworkFailure is the Dependency Graph Simulator's second,
	// read-only slice: which VMs declare an attachment to a managed network if
	// that logical network disappears. It combines separate ListNetworks and
	// ListVMs reads, so it is not an atomic snapshot. The entire request is
	// forwarded on a leader-hint rejection to avoid mixing nodes' FSM views.
	SimulateNetworkFailure(context.Context, *SimulateNetworkFailureRequest) (*SimulateNetworkFailureResponse, error)
	// TraceCellPath explains a VM Cell's intended outbound path to one
	// destination (ADR-0058). It is read-only and sends no probe. The
	// trace combines leader-authoritative VM/network intent with bounded
	// observations from the Cell's owner Hive, so results are sequential
	// and non-atomic. The entire request is leader-forwarded if the first
	// authoritative read rejects this node as a follower.
	TraceCellPath(context.Context, *TraceCellPathRequest) (*TraceCellPathResponse, error)
	// MigrateJail mirrors MigrateVM exactly, for jails instead of VMs -
	// see MigrateVM's own doc comment above for the full reasoning
	// (including the "target must already be a synced HAST replica"
	// safety requirement), which applies identically here.
	MigrateJail(context.Context, *MigrateJailRequest) (*MigrateJailResponse, error)
	// ReportVMPhase/ReportVMTeardownComplete/ReportJailPhase/
	// ReportJailTeardownComplete are peer-to-peer RPCs, not meant for
	// human/API-client use: a reconciler on a node that owns a VM/jail
	// but whose own raftd isn't the current raft leader calls these on
	// the LEADER node's managerd instead, since only the leader's own
	// raftd can ever accept an Apply (ADR-0029) - raftd's internal API
	// stays Unix-socket-only, never exposed over the network; this
	// reuses ManagerService's existing, already-networked, already-
	// optionally-API-key-gated external surface instead of opening a
	// new one. Gated by the same auth as every other RPC here when
	// enabled - see cmd/managerd's -peer-api-key flag.
	ReportVMPhase(context.Context, *ReportVMPhaseRequest) (*ReportVMPhaseResponse, error)
	ReportVMTeardownComplete(context.Context, *ReportVMTeardownCompleteRequest) (*ReportVMTeardownCompleteResponse, error)
	ReportJailPhase(context.Context, *ReportJailPhaseRequest) (*ReportJailPhaseResponse, error)
	ReportJailTeardownComplete(context.Context, *ReportJailTeardownCompleteRequest) (*ReportJailTeardownCompleteResponse, error)
	// PushISOTo is the peer-to-peer half of on-demand image fetching
	// (ADR-0041, superseding ADR-0040's browser-triggered ReplicateISO):
	// the *source* node's own managerd calls UploadISO against
	// target_node_id itself, the same way a browser upload would, in
	// response to a peer (usually a reconciler discovering it's missing
	// an ISO/base image a VM names) asking it to push a file it already
	// has. Peer-only, mirrors the Report* RPCs' own reasoning above
	// exactly - never meant for direct human/API-client use.
	PushISOTo(context.Context, *PushISOToRequest) (*PushISOToResponse, error)
	// GetLocalNetworkBridgeStatus reports THIS node's own local bridge
	// status for one network - built from RaftClient.ListNetworksLocal
	// (the already-replicated network config, read locally, never leader-
	// restricted) plus the local VLANStatus interface. Deliberately NOT
	// ListNetworks: that RPC is leader-only and forwards to the current
	// leader on a non-leader node, which would silently report the
	// LEADER's bridge state mislabeled as the queried node's own - see
	// ADR-0055 for the live bug this was built to avoid. Never forwards,
	// by construction.
	GetLocalNetworkBridgeStatus(context.Context, *GetLocalNetworkBridgeStatusRequest) (*GetLocalNetworkBridgeStatusResponse, error)
	// ListAssumptionResults reports THIS node's own persisted Automated
	// Assumption Checks (ADR-0055) - physical, per-node observational
	// data like HostStats/ISOs above, never routed through raft, and
	// never leader-forwarded (the same locality convention as HostStats).
	// See internal/assumptions/internal/assumecheck.
	ListAssumptionResults(context.Context, *ListAssumptionResultsRequest) (*ListAssumptionResultsResponse, error)
	mustEmbedUnimplementedManagerServiceServer()
}

// UnimplementedManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerServiceServer struct{}

func (UnimplementedManagerServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedManagerServiceServer) CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedManagerServiceServer) UpdateVM(context.Context, *UpdateVMRequest) (*UpdateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVM not implemented")
}
func (UnimplementedManagerServiceServer) DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedManagerServiceServer) ForcePurgeVM(context.Context, *ForcePurgeVMRequest) (*ForcePurgeVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForcePurgeVM not implemented")
}
func (UnimplementedManagerServiceServer) MigrateVM(context.Context, *MigrateVMRequest) (*MigrateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateVM not implemented")
}
func (UnimplementedManagerServiceServer) SetVMFirewallPaused(context.Context, *SetVMFirewallPausedRequest) (*SetVMFirewallPausedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVMFirewallPaused not implemented")
}
func (UnimplementedManagerServiceServer) GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVM not implemented")
}
func (UnimplementedManagerServiceServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedManagerServiceServer) UploadISO(grpc.ClientStreamingServer[UploadISORequest, UploadISOResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadISO not implemented")
}
func (UnimplementedManagerServiceServer) ListISOs(context.Context, *ListISOsRequest) (*ListISOsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListISOs not implemented")
}
func (UnimplementedManagerServiceServer) DeleteISO(context.Context, *DeleteISORequest) (*DeleteISOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteISO not implemented")
}
func (UnimplementedManagerServiceServer) HostStats(context.Context, *HostStatsRequest) (*HostStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HostStats not implemented")
}
func (UnimplementedManagerServiceServer) GetVMConsole(context.Context, *GetVMConsoleRequest) (*GetVMConsoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMConsole not implemented")
}
func (UnimplementedManagerServiceServer) GetVMSerialLog(context.Context, *GetVMSerialLogRequest) (*GetVMSerialLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMSerialLog not implemented")
}
func (UnimplementedManagerServiceServer) GetNodeConfig(context.Context, *GetNodeConfigRequest) (*GetNodeConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeConfig not implemented")
}
func (UnimplementedManagerServiceServer) UpdateNodeConfig(context.Context, *UpdateNodeConfigRequest) (*UpdateNodeConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNodeConfig not implemented")
}
func (UnimplementedManagerServiceServer) SetDatasetQuota(context.Context, *SetDatasetQuotaRequest) (*SetDatasetQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDatasetQuota not implemented")
}
func (UnimplementedManagerServiceServer) CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedManagerServiceServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedManagerServiceServer) DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNetwork not implemented")
}
func (UnimplementedManagerServiceServer) CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAPIKey not implemented")
}
func (UnimplementedManagerServiceServer) ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAPIKeys not implemented")
}
func (UnimplementedManagerServiceServer) RevokeAPIKey(context.Context, *RevokeAPIKeyRequest) (*RevokeAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAPIKey not implemented")
}
func (UnimplementedManagerServiceServer) CreateJail(context.Context, *CreateJailRequest) (*CreateJailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJail not implemented")
}
func (UnimplementedManagerServiceServer) UpdateJail(context.Context, *UpdateJailRequest) (*UpdateJailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJail not implemented")
}
func (UnimplementedManagerServiceServer) DeleteJail(context.Context, *DeleteJailRequest) (*DeleteJailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteJail not implemented")
}
func (UnimplementedManagerServiceServer) GetJail(context.Context, *GetJailRequest) (*GetJailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJail not implemented")
}
func (UnimplementedManagerServiceServer) ListJails(context.Context, *ListJailsRequest) (*ListJailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJails not implemented")
}
func (UnimplementedManagerServiceServer) ForcePurgeJail(context.Context, *ForcePurgeJailRequest) (*ForcePurgeJailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForcePurgeJail not implemented")
}
func (UnimplementedManagerServiceServer) SimulateNodeFailure(context.Context, *SimulateNodeFailureRequest) (*SimulateNodeFailureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateNodeFailure not implemented")
}
func (UnimplementedManagerServiceServer) SimulateNetworkFailure(context.Context, *SimulateNetworkFailureRequest) (*SimulateNetworkFailureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateNetworkFailure not implemented")
}
func (UnimplementedManagerServiceServer) TraceCellPath(context.Context, *TraceCellPathRequest) (*TraceCellPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TraceCellPath not implemented")
}
func (UnimplementedManagerServiceServer) MigrateJail(context.Context, *MigrateJailRequest) (*MigrateJailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateJail not implemented")
}
func (UnimplementedManagerServiceServer) ReportVMPhase(context.Context, *ReportVMPhaseRequest) (*ReportVMPhaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportVMPhase not implemented")
}
func (UnimplementedManagerServiceServer) ReportVMTeardownComplete(context.Context, *ReportVMTeardownCompleteRequest) (*ReportVMTeardownCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportVMTeardownComplete not implemented")
}
func (UnimplementedManagerServiceServer) ReportJailPhase(context.Context, *ReportJailPhaseRequest) (*ReportJailPhaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportJailPhase not implemented")
}
func (UnimplementedManagerServiceServer) ReportJailTeardownComplete(context.Context, *ReportJailTeardownCompleteRequest) (*ReportJailTeardownCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportJailTeardownComplete not implemented")
}
func (UnimplementedManagerServiceServer) PushISOTo(context.Context, *PushISOToRequest) (*PushISOToResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushISOTo not implemented")
}
func (UnimplementedManagerServiceServer) GetLocalNetworkBridgeStatus(context.Context, *GetLocalNetworkBridgeStatusRequest) (*GetLocalNetworkBridgeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLocalNetworkBridgeStatus not implemented")
}
func (UnimplementedManagerServiceServer) ListAssumptionResults(context.Context, *ListAssumptionResultsRequest) (*ListAssumptionResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssumptionResults not implemented")
}
func (UnimplementedManagerServiceServer) mustEmbedUnimplementedManagerServiceServer() {}
func (UnimplementedManagerServiceServer) testEmbeddedByValue()                        {}

// UnsafeManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerServiceServer will
// result in compilation errors.
type UnsafeManagerServiceServer interface {
	mustEmbedUnimplementedManagerServiceServer()
}

func RegisterManagerServiceServer(s grpc.ServiceRegistrar, srv ManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerService_ServiceDesc, srv)
}

func _ManagerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_UpdateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).UpdateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_UpdateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).UpdateVM(ctx, req.(*UpdateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ForcePurgeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForcePurgeVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ForcePurgeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ForcePurgeVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ForcePurgeVM(ctx, req.(*ForcePurgeVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_MigrateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).MigrateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_MigrateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).MigrateVM(ctx, req.(*MigrateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_SetVMFirewallPaused_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVMFirewallPausedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).SetVMFirewallPaused(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_SetVMFirewallPaused_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).SetVMFirewallPaused(ctx, req.(*SetVMFirewallPausedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetVM(ctx, req.(*GetVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_UploadISO_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagerServiceServer).UploadISO(&grpc.GenericServerStream[UploadISORequest, UploadISOResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerService_UploadISOServer = grpc.ClientStreamingServer[UploadISORequest, UploadISOResponse]

func _ManagerService_ListISOs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListISOsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListISOs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListISOs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListISOs(ctx, req.(*ListISOsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DeleteISO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteISORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DeleteISO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_DeleteISO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DeleteISO(ctx, req.(*DeleteISORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_HostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).HostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_HostStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).HostStats(ctx, req.(*HostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetVMConsole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMConsoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetVMConsole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetVMConsole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetVMConsole(ctx, req.(*GetVMConsoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetVMSerialLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMSerialLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetVMSerialLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetVMSerialLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetVMSerialLog(ctx, req.(*GetVMSerialLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetNodeConfig(ctx, req.(*GetNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_UpdateNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).UpdateNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_UpdateNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).UpdateNodeConfig(ctx, req.(*UpdateNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_SetDatasetQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDatasetQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).SetDatasetQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_SetDatasetQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).SetDatasetQuota(ctx, req.(*SetDatasetQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CreateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_DeleteNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CreateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CreateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CreateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CreateAPIKey(ctx, req.(*CreateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListAPIKeys(ctx, req.(*ListAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_RevokeAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).RevokeAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_RevokeAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).RevokeAPIKey(ctx, req.(*RevokeAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_CreateJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).CreateJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_CreateJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).CreateJail(ctx, req.(*CreateJailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_UpdateJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).UpdateJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_UpdateJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).UpdateJail(ctx, req.(*UpdateJailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DeleteJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DeleteJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_DeleteJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DeleteJail(ctx, req.(*DeleteJailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetJail(ctx, req.(*GetJailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListJails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListJails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListJails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListJails(ctx, req.(*ListJailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ForcePurgeJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForcePurgeJailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ForcePurgeJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ForcePurgeJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ForcePurgeJail(ctx, req.(*ForcePurgeJailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_SimulateNodeFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateNodeFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).SimulateNodeFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_SimulateNodeFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).SimulateNodeFailure(ctx, req.(*SimulateNodeFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_SimulateNetworkFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateNetworkFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).SimulateNetworkFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_SimulateNetworkFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).SimulateNetworkFailure(ctx, req.(*SimulateNetworkFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_TraceCellPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceCellPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).TraceCellPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_TraceCellPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).TraceCellPath(ctx, req.(*TraceCellPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_MigrateJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateJailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).MigrateJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_MigrateJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).MigrateJail(ctx, req.(*MigrateJailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ReportVMPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportVMPhaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ReportVMPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ReportVMPhase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ReportVMPhase(ctx, req.(*ReportVMPhaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ReportVMTeardownComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportVMTeardownCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ReportVMTeardownComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ReportVMTeardownComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ReportVMTeardownComplete(ctx, req.(*ReportVMTeardownCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ReportJailPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportJailPhaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ReportJailPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ReportJailPhase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ReportJailPhase(ctx, req.(*ReportJailPhaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ReportJailTeardownComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportJailTeardownCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ReportJailTeardownComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ReportJailTeardownComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ReportJailTeardownComplete(ctx, req.(*ReportJailTeardownCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_PushISOTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushISOToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).PushISOTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_PushISOTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).PushISOTo(ctx, req.(*PushISOToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_GetLocalNetworkBridgeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalNetworkBridgeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).GetLocalNetworkBridgeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_GetLocalNetworkBridgeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).GetLocalNetworkBridgeStatus(ctx, req.(*GetLocalNetworkBridgeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_ListAssumptionResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssumptionResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).ListAssumptionResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagerService_ListAssumptionResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).ListAssumptionResults(ctx, req.(*ListAssumptionResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagerService_ServiceDesc is the grpc.ServiceDesc for ManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apiary.rpc.v1.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ManagerService_Status_Handler,
		},
		{
			MethodName: "CreateVM",
			Handler:    _ManagerService_CreateVM_Handler,
		},
		{
			MethodName: "UpdateVM",
			Handler:    _ManagerService_UpdateVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _ManagerService_DeleteVM_Handler,
		},
		{
			MethodName: "ForcePurgeVM",
			Handler:    _ManagerService_ForcePurgeVM_Handler,
		},
		{
			MethodName: "MigrateVM",
			Handler:    _ManagerService_MigrateVM_Handler,
		},
		{
			MethodName: "SetVMFirewallPaused",
			Handler:    _ManagerService_SetVMFirewallPaused_Handler,
		},
		{
			MethodName: "GetVM",
			Handler:    _ManagerService_GetVM_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _ManagerService_ListVMs_Handler,
		},
		{
			MethodName: "ListISOs",
			Handler:    _ManagerService_ListISOs_Handler,
		},
		{
			MethodName: "DeleteISO",
			Handler:    _ManagerService_DeleteISO_Handler,
		},
		{
			MethodName: "HostStats",
			Handler:    _ManagerService_HostStats_Handler,
		},
		{
			MethodName: "GetVMConsole",
			Handler:    _ManagerService_GetVMConsole_Handler,
		},
		{
			MethodName: "GetVMSerialLog",
			Handler:    _ManagerService_GetVMSerialLog_Handler,
		},
		{
			MethodName: "GetNodeConfig",
			Handler:    _ManagerService_GetNodeConfig_Handler,
		},
		{
			MethodName: "UpdateNodeConfig",
			Handler:    _ManagerService_UpdateNodeConfig_Handler,
		},
		{
			MethodName: "SetDatasetQuota",
			Handler:    _ManagerService_SetDatasetQuota_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _ManagerService_CreateNetwork_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _ManagerService_ListNetworks_Handler,
		},
		{
			MethodName: "DeleteNetwork",
			Handler:    _ManagerService_DeleteNetwork_Handler,
		},
		{
			MethodName: "CreateAPIKey",
			Handler:    _ManagerService_CreateAPIKey_Handler,
		},
		{
			MethodName: "ListAPIKeys",
			Handler:    _ManagerService_ListAPIKeys_Handler,
		},
		{
			MethodName: "RevokeAPIKey",
			Handler:    _ManagerService_RevokeAPIKey_Handler,
		},
		{
			MethodName: "CreateJail",
			Handler:    _ManagerService_CreateJail_Handler,
		},
		{
			MethodName: "UpdateJail",
			Handler:    _ManagerService_UpdateJail_Handler,
		},
		{
			MethodName: "DeleteJail",
			Handler:    _ManagerService_DeleteJail_Handler,
		},
		{
			MethodName: "GetJail",
			Handler:    _ManagerService_GetJail_Handler,
		},
		{
			MethodName: "ListJails",
			Handler:    _ManagerService_ListJails_Handler,
		},
		{
			MethodName: "ForcePurgeJail",
			Handler:    _ManagerService_ForcePurgeJail_Handler,
		},
		{
			MethodName: "SimulateNodeFailure",
			Handler:    _ManagerService_SimulateNodeFailure_Handler,
		},
		{
			MethodName: "SimulateNetworkFailure",
			Handler:    _ManagerService_SimulateNetworkFailure_Handler,
		},
		{
			MethodName: "TraceCellPath",
			Handler:    _ManagerService_TraceCellPath_Handler,
		},
		{
			MethodName: "MigrateJail",
			Handler:    _ManagerService_MigrateJail_Handler,
		},
		{
			MethodName: "ReportVMPhase",
			Handler:    _ManagerService_ReportVMPhase_Handler,
		},
		{
			MethodName: "ReportVMTeardownComplete",
			Handler:    _ManagerService_ReportVMTeardownComplete_Handler,
		},
		{
			MethodName: "ReportJailPhase",
			Handler:    _ManagerService_ReportJailPhase_Handler,
		},
		{
			MethodName: "ReportJailTeardownComplete",
			Handler:    _ManagerService_ReportJailTeardownComplete_Handler,
		},
		{
			MethodName: "PushISOTo",
			Handler:    _ManagerService_PushISOTo_Handler,
		},
		{
			MethodName: "GetLocalNetworkBridgeStatus",
			Handler:    _ManagerService_GetLocalNetworkBridgeStatus_Handler,
		},
		{
			MethodName: "ListAssumptionResults",
			Handler:    _ManagerService_ListAssumptionResults_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadISO",
			Handler:       _ManagerService_UploadISO_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/rpc/manager.proto",
}
