// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/rpc/manager.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manager_node_id identifies this managerd instance. It may differ from
	// the raft node ID it talks to.
	ManagerNodeId string `protobuf:"bytes,1,opt,name=manager_node_id,json=managerNodeId,proto3" json:"manager_node_id,omitempty"`
	// raft_reachable is false if managerd could not reach raftd over the
	// internal socket for this request; raft_error explains why, and the
	// remaining raft_* fields are left at their zero values.
	RaftReachable    bool   `protobuf:"varint,2,opt,name=raft_reachable,json=raftReachable,proto3" json:"raft_reachable,omitempty"`
	RaftError        string `protobuf:"bytes,3,opt,name=raft_error,json=raftError,proto3" json:"raft_error,omitempty"`
	RaftIsLeader     bool   `protobuf:"varint,4,opt,name=raft_is_leader,json=raftIsLeader,proto3" json:"raft_is_leader,omitempty"`
	RaftLeaderId     string `protobuf:"bytes,5,opt,name=raft_leader_id,json=raftLeaderId,proto3" json:"raft_leader_id,omitempty"`
	RaftNodeId       string `protobuf:"bytes,6,opt,name=raft_node_id,json=raftNodeId,proto3" json:"raft_node_id,omitempty"`
	RaftLastLogIndex uint64 `protobuf:"varint,7,opt,name=raft_last_log_index,json=raftLastLogIndex,proto3" json:"raft_last_log_index,omitempty"`
	RaftAppliedIndex uint64 `protobuf:"varint,8,opt,name=raft_applied_index,json=raftAppliedIndex,proto3" json:"raft_applied_index,omitempty"`
	RaftState        string `protobuf:"bytes,9,opt,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetManagerNodeId() string {
	if x != nil {
		return x.ManagerNodeId
	}
	return ""
}

func (x *StatusResponse) GetRaftReachable() bool {
	if x != nil {
		return x.RaftReachable
	}
	return false
}

func (x *StatusResponse) GetRaftError() string {
	if x != nil {
		return x.RaftError
	}
	return ""
}

func (x *StatusResponse) GetRaftIsLeader() bool {
	if x != nil {
		return x.RaftIsLeader
	}
	return false
}

func (x *StatusResponse) GetRaftLeaderId() string {
	if x != nil {
		return x.RaftLeaderId
	}
	return ""
}

func (x *StatusResponse) GetRaftNodeId() string {
	if x != nil {
		return x.RaftNodeId
	}
	return ""
}

func (x *StatusResponse) GetRaftLastLogIndex() uint64 {
	if x != nil {
		return x.RaftLastLogIndex
	}
	return 0
}

func (x *StatusResponse) GetRaftAppliedIndex() uint64 {
	if x != nil {
		return x.RaftAppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetRaftState() string {
	if x != nil {
		return x.RaftState
	}
	return ""
}

var File_api_rpc_manager_proto protoreflect.FileDescriptor

const file_api_rpc_manager_proto_rawDesc = "" +
	"\n" +
	"\x15api/rpc/manager.proto\x12\rapiary.rpc.v1\"\x0f\n" +
	"\rStatusRequest\"\xe8\x02\n" +
	"\x0eStatusResponse\x12&\n" +
	"\x0fmanager_node_id\x18\x01 \x01(\tR\rmanagerNodeId\x12%\n" +
	"\x0eraft_reachable\x18\x02 \x01(\bR\rraftReachable\x12\x1d\n" +
	"\n" +
	"raft_error\x18\x03 \x01(\tR\traftError\x12$\n" +
	"\x0eraft_is_leader\x18\x04 \x01(\bR\fraftIsLeader\x12$\n" +
	"\x0eraft_leader_id\x18\x05 \x01(\tR\fraftLeaderId\x12 \n" +
	"\fraft_node_id\x18\x06 \x01(\tR\n" +
	"raftNodeId\x12-\n" +
	"\x13raft_last_log_index\x18\a \x01(\x04R\x10raftLastLogIndex\x12,\n" +
	"\x12raft_applied_index\x18\b \x01(\x04R\x10raftAppliedIndex\x12\x1d\n" +
	"\n" +
	"raft_state\x18\t \x01(\tR\traftState2W\n" +
	"\x0eManagerService\x12E\n" +
	"\x06Status\x12\x1c.apiary.rpc.v1.StatusRequest\x1a\x1d.apiary.rpc.v1.StatusResponseB-Z+github.com/glenjbarber/apiary/api/rpc;rpcpbb\x06proto3"

var (
	file_api_rpc_manager_proto_rawDescOnce sync.Once
	file_api_rpc_manager_proto_rawDescData []byte
)

func file_api_rpc_manager_proto_rawDescGZIP() []byte {
	file_api_rpc_manager_proto_rawDescOnce.Do(func() {
		file_api_rpc_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rpc_manager_proto_rawDesc), len(file_api_rpc_manager_proto_rawDesc)))
	})
	return file_api_rpc_manager_proto_rawDescData
}

var file_api_rpc_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_rpc_manager_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: apiary.rpc.v1.StatusRequest
	(*StatusResponse)(nil), // 1: apiary.rpc.v1.StatusResponse
}
var file_api_rpc_manager_proto_depIdxs = []int32{
	0, // 0: apiary.rpc.v1.ManagerService.Status:input_type -> apiary.rpc.v1.StatusRequest
	1, // 1: apiary.rpc.v1.ManagerService.Status:output_type -> apiary.rpc.v1.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_rpc_manager_proto_init() }
func file_api_rpc_manager_proto_init() {
	if File_api_rpc_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rpc_manager_proto_rawDesc), len(file_api_rpc_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rpc_manager_proto_goTypes,
		DependencyIndexes: file_api_rpc_manager_proto_depIdxs,
		MessageInfos:      file_api_rpc_manager_proto_msgTypes,
	}.Build()
	File_api_rpc_manager_proto = out.File
	file_api_rpc_manager_proto_goTypes = nil
	file_api_rpc_manager_proto_depIdxs = nil
}
