// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/rpc/manager.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VMState mirrors api/internalpb's VMState. Kept as a separate type
// (rather than reusing the internal package's) so the external schema
// doesn't couple to the internal protocol's evolution - the same
// reasoning ADR-0002 applied to StatusResponse.
type VMState int32

const (
	VMState_VM_STATE_UNSPECIFIED VMState = 0
	VMState_VM_STATE_STOPPED     VMState = 1
	VMState_VM_STATE_RUNNING     VMState = 2
	// VM_STATE_DELETING means the VM has been requested for deletion and
	// its owning node's reconciler is (or will be) tearing down its real
	// resources - see ADR-0016. The record disappears from ListVMs once
	// that completes.
	VMState_VM_STATE_DELETING VMState = 3
)

// Enum value maps for VMState.
var (
	VMState_name = map[int32]string{
		0: "VM_STATE_UNSPECIFIED",
		1: "VM_STATE_STOPPED",
		2: "VM_STATE_RUNNING",
		3: "VM_STATE_DELETING",
	}
	VMState_value = map[string]int32{
		"VM_STATE_UNSPECIFIED": 0,
		"VM_STATE_STOPPED":     1,
		"VM_STATE_RUNNING":     2,
		"VM_STATE_DELETING":    3,
	}
)

func (x VMState) Enum() *VMState {
	p := new(VMState)
	*p = x
	return p
}

func (x VMState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rpc_manager_proto_enumTypes[0].Descriptor()
}

func (VMState) Type() protoreflect.EnumType {
	return &file_api_rpc_manager_proto_enumTypes[0]
}

func (x VMState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMState.Descriptor instead.
func (VMState) EnumDescriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{0}
}

// VMPhase mirrors api/internalpb's VMPhase: the reconciler's own observed
// progress toward a VM's desired state, as opposed to desired_state
// (which is only ever what a caller asked for).
type VMPhase int32

const (
	VMPhase_VM_PHASE_UNSPECIFIED VMPhase = 0
	VMPhase_VM_PHASE_CREATING    VMPhase = 1
	VMPhase_VM_PHASE_READY       VMPhase = 2
	VMPhase_VM_PHASE_DELETING    VMPhase = 3
	VMPhase_VM_PHASE_ERROR       VMPhase = 4
)

// Enum value maps for VMPhase.
var (
	VMPhase_name = map[int32]string{
		0: "VM_PHASE_UNSPECIFIED",
		1: "VM_PHASE_CREATING",
		2: "VM_PHASE_READY",
		3: "VM_PHASE_DELETING",
		4: "VM_PHASE_ERROR",
	}
	VMPhase_value = map[string]int32{
		"VM_PHASE_UNSPECIFIED": 0,
		"VM_PHASE_CREATING":    1,
		"VM_PHASE_READY":       2,
		"VM_PHASE_DELETING":    3,
		"VM_PHASE_ERROR":       4,
	}
)

func (x VMPhase) Enum() *VMPhase {
	p := new(VMPhase)
	*p = x
	return p
}

func (x VMPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rpc_manager_proto_enumTypes[1].Descriptor()
}

func (VMPhase) Type() protoreflect.EnumType {
	return &file_api_rpc_manager_proto_enumTypes[1]
}

func (x VMPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMPhase.Descriptor instead.
func (VMPhase) EnumDescriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{1}
}

type VMDefinition struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vcpus        uint32                 `protobuf:"varint,3,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb     uint64                 `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	NodeId       string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DesiredState VMState                `protobuf:"varint,6,opt,name=desired_state,json=desiredState,proto3,enum=apiary.rpc.v1.VMState" json:"desired_state,omitempty"`
	Phase        VMPhase                `protobuf:"varint,7,opt,name=phase,proto3,enum=apiary.rpc.v1.VMPhase" json:"phase,omitempty"`
	PhaseError   string                 `protobuf:"bytes,8,opt,name=phase_error,json=phaseError,proto3" json:"phase_error,omitempty"`
	// iso_name, if set, names an image already uploaded via UploadISO on
	// the assigned node - the reconciler resolves it to a local path and
	// attaches it as a CD-ROM device. Empty means no installer image
	// (the VM's disk is used as-is).
	IsoName       string `protobuf:"bytes,9,opt,name=iso_name,json=isoName,proto3" json:"iso_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMDefinition) Reset() {
	*x = VMDefinition{}
	mi := &file_api_rpc_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMDefinition) ProtoMessage() {}

func (x *VMDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMDefinition.ProtoReflect.Descriptor instead.
func (*VMDefinition) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{0}
}

func (x *VMDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VMDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMDefinition) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VMDefinition) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VMDefinition) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VMDefinition) GetDesiredState() VMState {
	if x != nil {
		return x.DesiredState
	}
	return VMState_VM_STATE_UNSPECIFIED
}

func (x *VMDefinition) GetPhase() VMPhase {
	if x != nil {
		return x.Phase
	}
	return VMPhase_VM_PHASE_UNSPECIFIED
}

func (x *VMDefinition) GetPhaseError() string {
	if x != nil {
		return x.PhaseError
	}
	return ""
}

func (x *VMDefinition) GetIsoName() string {
	if x != nil {
		return x.IsoName
	}
	return ""
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMDefinition          `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVMRequest) GetVm() *VMDefinition {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *CreateVMRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type CreateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMDefinition          `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResponse) Reset() {
	*x = CreateVMResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResponse) ProtoMessage() {}

func (x *CreateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResponse.ProtoReflect.Descriptor instead.
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVMResponse) GetVm() *VMDefinition {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *CreateVMResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateVMResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type UpdateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMDefinition          `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVMRequest) Reset() {
	*x = UpdateVMRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVMRequest) ProtoMessage() {}

func (x *UpdateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVMRequest.ProtoReflect.Descriptor instead.
func (*UpdateVMRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateVMRequest) GetVm() *VMDefinition {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *UpdateVMRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type UpdateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMDefinition          `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVMResponse) Reset() {
	*x = UpdateVMResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVMResponse) ProtoMessage() {}

func (x *UpdateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVMResponse.ProtoReflect.Descriptor instead.
func (*UpdateVMResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateVMResponse) GetVm() *VMDefinition {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *UpdateVMResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateVMResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type DeleteVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMRequest) Reset() {
	*x = DeleteVMRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMRequest) ProtoMessage() {}

func (x *DeleteVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMRequest.ProtoReflect.Descriptor instead.
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteVMRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteVMRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DeleteVMResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// vm is the definition that was deleted, echoed back for confirmation.
	Vm            *VMDefinition `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Error         string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LeaderHint    string        `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMResponse) Reset() {
	*x = DeleteVMResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMResponse) ProtoMessage() {}

func (x *DeleteVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMResponse.ProtoReflect.Descriptor instead.
func (*DeleteVMResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVMResponse) GetVm() *VMDefinition {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *DeleteVMResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteVMResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type GetVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{7}
}

func (x *GetVMRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMDefinition          `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,4,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMResponse) Reset() {
	*x = GetVMResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMResponse) ProtoMessage() {}

func (x *GetVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMResponse.ProtoReflect.Descriptor instead.
func (*GetVMResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{8}
}

func (x *GetVMResponse) GetVm() *VMDefinition {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *GetVMResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetVMResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetVMResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{9}
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMDefinition        `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{10}
}

func (x *ListVMsResponse) GetVms() []*VMDefinition {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *ListVMsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListVMsResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{11}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manager_node_id identifies this managerd instance. It may differ from
	// the raft node ID it talks to.
	ManagerNodeId string `protobuf:"bytes,1,opt,name=manager_node_id,json=managerNodeId,proto3" json:"manager_node_id,omitempty"`
	// raft_reachable is false if managerd could not reach raftd over the
	// internal socket for this request; raft_error explains why, and the
	// remaining raft_* fields are left at their zero values.
	RaftReachable    bool   `protobuf:"varint,2,opt,name=raft_reachable,json=raftReachable,proto3" json:"raft_reachable,omitempty"`
	RaftError        string `protobuf:"bytes,3,opt,name=raft_error,json=raftError,proto3" json:"raft_error,omitempty"`
	RaftIsLeader     bool   `protobuf:"varint,4,opt,name=raft_is_leader,json=raftIsLeader,proto3" json:"raft_is_leader,omitempty"`
	RaftLeaderId     string `protobuf:"bytes,5,opt,name=raft_leader_id,json=raftLeaderId,proto3" json:"raft_leader_id,omitempty"`
	RaftNodeId       string `protobuf:"bytes,6,opt,name=raft_node_id,json=raftNodeId,proto3" json:"raft_node_id,omitempty"`
	RaftLastLogIndex uint64 `protobuf:"varint,7,opt,name=raft_last_log_index,json=raftLastLogIndex,proto3" json:"raft_last_log_index,omitempty"`
	RaftAppliedIndex uint64 `protobuf:"varint,8,opt,name=raft_applied_index,json=raftAppliedIndex,proto3" json:"raft_applied_index,omitempty"`
	RaftState        string `protobuf:"bytes,9,opt,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty"`
	// known_node_ids lists the IDs of raft cluster members, as known to
	// this node's raftd. Useful for clients (e.g. the web UI) that need to
	// offer a choice of nodes without a separate scheduling component.
	KnownNodeIds  []string `protobuf:"bytes,10,rep,name=known_node_ids,json=knownNodeIds,proto3" json:"known_node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetManagerNodeId() string {
	if x != nil {
		return x.ManagerNodeId
	}
	return ""
}

func (x *StatusResponse) GetRaftReachable() bool {
	if x != nil {
		return x.RaftReachable
	}
	return false
}

func (x *StatusResponse) GetRaftError() string {
	if x != nil {
		return x.RaftError
	}
	return ""
}

func (x *StatusResponse) GetRaftIsLeader() bool {
	if x != nil {
		return x.RaftIsLeader
	}
	return false
}

func (x *StatusResponse) GetRaftLeaderId() string {
	if x != nil {
		return x.RaftLeaderId
	}
	return ""
}

func (x *StatusResponse) GetRaftNodeId() string {
	if x != nil {
		return x.RaftNodeId
	}
	return ""
}

func (x *StatusResponse) GetRaftLastLogIndex() uint64 {
	if x != nil {
		return x.RaftLastLogIndex
	}
	return 0
}

func (x *StatusResponse) GetRaftAppliedIndex() uint64 {
	if x != nil {
		return x.RaftAppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetRaftState() string {
	if x != nil {
		return x.RaftState
	}
	return ""
}

func (x *StatusResponse) GetKnownNodeIds() []string {
	if x != nil {
		return x.KnownNodeIds
	}
	return nil
}

// UploadISORequest is one message in the UploadISO client stream.
// Exactly one metadata message must come first, followed by one or
// more chunk messages carrying the file's bytes in order.
type UploadISORequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadISORequest_Metadata
	//	*UploadISORequest_Chunk
	Data          isUploadISORequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadISORequest) Reset() {
	*x = UploadISORequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadISORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadISORequest) ProtoMessage() {}

func (x *UploadISORequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadISORequest.ProtoReflect.Descriptor instead.
func (*UploadISORequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{13}
}

func (x *UploadISORequest) GetData() isUploadISORequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadISORequest) GetMetadata() *ISOUploadMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadISORequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadISORequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadISORequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadISORequest_Data interface {
	isUploadISORequest_Data()
}

type UploadISORequest_Metadata struct {
	Metadata *ISOUploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadISORequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadISORequest_Metadata) isUploadISORequest_Data() {}

func (*UploadISORequest_Chunk) isUploadISORequest_Data() {}

type ISOUploadMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// expected_sha256 is required (see ADR-0017) - an upload with no hash
	// to verify against is exactly the failure mode this API exists to
	// prevent.
	ExpectedSha256 string `protobuf:"bytes,2,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ISOUploadMetadata) Reset() {
	*x = ISOUploadMetadata{}
	mi := &file_api_rpc_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISOUploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISOUploadMetadata) ProtoMessage() {}

func (x *ISOUploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISOUploadMetadata.ProtoReflect.Descriptor instead.
func (*ISOUploadMetadata) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{14}
}

func (x *ISOUploadMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ISOUploadMetadata) GetExpectedSha256() string {
	if x != nil {
		return x.ExpectedSha256
	}
	return ""
}

type UploadISOResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256    string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// error is set (with name/size_bytes/sha256 left at zero values) if
	// the upload was rejected - most commonly a hash mismatch.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadISOResponse) Reset() {
	*x = UploadISOResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadISOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadISOResponse) ProtoMessage() {}

func (x *UploadISOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadISOResponse.ProtoReflect.Descriptor instead.
func (*UploadISOResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{15}
}

func (x *UploadISOResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadISOResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *UploadISOResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadISOResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListISOsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListISOsRequest) Reset() {
	*x = ListISOsRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListISOsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListISOsRequest) ProtoMessage() {}

func (x *ListISOsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListISOsRequest.ProtoReflect.Descriptor instead.
func (*ListISOsRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{16}
}

type ISOInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISOInfo) Reset() {
	*x = ISOInfo{}
	mi := &file_api_rpc_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISOInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISOInfo) ProtoMessage() {}

func (x *ISOInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISOInfo.ProtoReflect.Descriptor instead.
func (*ISOInfo) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{17}
}

func (x *ISOInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ISOInfo) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ISOInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ListISOsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isos          []*ISOInfo             `protobuf:"bytes,1,rep,name=isos,proto3" json:"isos,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListISOsResponse) Reset() {
	*x = ListISOsResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListISOsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListISOsResponse) ProtoMessage() {}

func (x *ListISOsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListISOsResponse.ProtoReflect.Descriptor instead.
func (*ListISOsResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{18}
}

func (x *ListISOsResponse) GetIsos() []*ISOInfo {
	if x != nil {
		return x.Isos
	}
	return nil
}

func (x *ListISOsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteISORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteISORequest) Reset() {
	*x = DeleteISORequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteISORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteISORequest) ProtoMessage() {}

func (x *DeleteISORequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteISORequest.ProtoReflect.Descriptor instead.
func (*DeleteISORequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteISORequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteISOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteISOResponse) Reset() {
	*x = DeleteISOResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteISOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteISOResponse) ProtoMessage() {}

func (x *DeleteISOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteISOResponse.ProtoReflect.Descriptor instead.
func (*DeleteISOResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteISOResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStatsRequest) Reset() {
	*x = HostStatsRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStatsRequest) ProtoMessage() {}

func (x *HostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStatsRequest.ProtoReflect.Descriptor instead.
func (*HostStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{21}
}

type CPUStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cores         int32                  `protobuf:"varint,1,opt,name=cores,proto3" json:"cores,omitempty"`
	LoadAvg_1     float64                `protobuf:"fixed64,2,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5     float64                `protobuf:"fixed64,3,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15    float64                `protobuf:"fixed64,4,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUStats) Reset() {
	*x = CPUStats{}
	mi := &file_api_rpc_manager_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUStats) ProtoMessage() {}

func (x *CPUStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUStats.ProtoReflect.Descriptor instead.
func (*CPUStats) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{22}
}

func (x *CPUStats) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUStats) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *CPUStats) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *CPUStats) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

type MemStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes    uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,2,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemStats) Reset() {
	*x = MemStats{}
	mi := &file_api_rpc_manager_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemStats) ProtoMessage() {}

func (x *MemStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemStats.ProtoReflect.Descriptor instead.
func (*MemStats) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{23}
}

func (x *MemStats) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemStats) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type PoolStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	AllocBytes    uint64                 `protobuf:"varint,3,opt,name=alloc_bytes,json=allocBytes,proto3" json:"alloc_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	CapacityPct   uint32                 `protobuf:"varint,5,opt,name=capacity_pct,json=capacityPct,proto3" json:"capacity_pct,omitempty"`
	Health        string                 `protobuf:"bytes,6,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolStats) Reset() {
	*x = PoolStats{}
	mi := &file_api_rpc_manager_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStats) ProtoMessage() {}

func (x *PoolStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStats.ProtoReflect.Descriptor instead.
func (*PoolStats) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{24}
}

func (x *PoolStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PoolStats) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PoolStats) GetAllocBytes() uint64 {
	if x != nil {
		return x.AllocBytes
	}
	return 0
}

func (x *PoolStats) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *PoolStats) GetCapacityPct() uint32 {
	if x != nil {
		return x.CapacityPct
	}
	return 0
}

func (x *PoolStats) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

type DiskStats struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Model   string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Serial  string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Healthy bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// error is set if the SMART query for this disk failed - healthy is
	// meaningless in that case, not a false "known bad" signal.
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStats) Reset() {
	*x = DiskStats{}
	mi := &file_api_rpc_manager_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStats) ProtoMessage() {}

func (x *DiskStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStats.ProtoReflect.Descriptor instead.
func (*DiskStats) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{25}
}

func (x *DiskStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskStats) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DiskStats) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DiskStats) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *DiskStats) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NetIfaceStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// rx_bytes/tx_bytes are cumulative counters since boot, not a rate -
	// see internal/hoststats.NetIface's doc comment (ADR-0018).
	RxBytes       uint64 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetIfaceStats) Reset() {
	*x = NetIfaceStats{}
	mi := &file_api_rpc_manager_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetIfaceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetIfaceStats) ProtoMessage() {}

func (x *NetIfaceStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetIfaceStats.ProtoReflect.Descriptor instead.
func (*NetIfaceStats) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{26}
}

func (x *NetIfaceStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetIfaceStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetIfaceStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

type HostStatsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Cpu    *CPUStats              `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem    *MemStats              `protobuf:"bytes,3,opt,name=mem,proto3" json:"mem,omitempty"`
	Pools  []*PoolStats           `protobuf:"bytes,4,rep,name=pools,proto3" json:"pools,omitempty"`
	Disks  []*DiskStats           `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Net    []*NetIfaceStats       `protobuf:"bytes,6,rep,name=net,proto3" json:"net,omitempty"`
	// errors lists any subsystem that failed to report (see
	// hoststats.Snapshot.Errors) - the rest of the response is still
	// populated on a best-effort basis.
	Errors        []string `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStatsResponse) Reset() {
	*x = HostStatsResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStatsResponse) ProtoMessage() {}

func (x *HostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStatsResponse.ProtoReflect.Descriptor instead.
func (*HostStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{27}
}

func (x *HostStatsResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HostStatsResponse) GetCpu() *CPUStats {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *HostStatsResponse) GetMem() *MemStats {
	if x != nil {
		return x.Mem
	}
	return nil
}

func (x *HostStatsResponse) GetPools() []*PoolStats {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *HostStatsResponse) GetDisks() []*DiskStats {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *HostStatsResponse) GetNet() []*NetIfaceStats {
	if x != nil {
		return x.Net
	}
	return nil
}

func (x *HostStatsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetVMConsoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMConsoleRequest) Reset() {
	*x = GetVMConsoleRequest{}
	mi := &file_api_rpc_manager_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMConsoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMConsoleRequest) ProtoMessage() {}

func (x *GetVMConsoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMConsoleRequest.ProtoReflect.Descriptor instead.
func (*GetVMConsoleRequest) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{28}
}

func (x *GetVMConsoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVMConsoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host/port identify the VNC TCP listener to connect to -
	// internal/frontend proxies its noVNC WebSocket console through this,
	// never exposing it directly to the browser. host is the owning node's
	// ID, which this v1 assumes is a resolvable hostname (true for every
	// node in this project today, since node IDs default to os.Hostname())
	// - a real multi-node deployment with non-resolvable node IDs would
	// need real node-address discovery, which doesn't exist yet (the same
	// gap already noted for node scheduling).
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// available is false (with host/port left at zero values) if the VM
	// isn't running with VNC on this node - not yet reconciled, running on
	// a different node, or created before VNC support existed.
	Available     bool   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMConsoleResponse) Reset() {
	*x = GetVMConsoleResponse{}
	mi := &file_api_rpc_manager_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMConsoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMConsoleResponse) ProtoMessage() {}

func (x *GetVMConsoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpc_manager_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMConsoleResponse.ProtoReflect.Descriptor instead.
func (*GetVMConsoleResponse) Descriptor() ([]byte, []int) {
	return file_api_rpc_manager_proto_rawDescGZIP(), []int{29}
}

func (x *GetVMConsoleResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetVMConsoleResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GetVMConsoleResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *GetVMConsoleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_rpc_manager_proto protoreflect.FileDescriptor

const file_api_rpc_manager_proto_rawDesc = "" +
	"\n" +
	"\x15api/rpc/manager.proto\x12\rapiary.rpc.v1\"\xa5\x02\n" +
	"\fVMDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05vcpus\x18\x03 \x01(\rR\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x04R\bmemoryMb\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12;\n" +
	"\rdesired_state\x18\x06 \x01(\x0e2\x16.apiary.rpc.v1.VMStateR\fdesiredState\x12,\n" +
	"\x05phase\x18\a \x01(\x0e2\x16.apiary.rpc.v1.VMPhaseR\x05phase\x12\x1f\n" +
	"\vphase_error\x18\b \x01(\tR\n" +
	"phaseError\x12\x19\n" +
	"\biso_name\x18\t \x01(\tR\aisoName\"]\n" +
	"\x0fCreateVMRequest\x12+\n" +
	"\x02vm\x18\x01 \x01(\v2\x1b.apiary.rpc.v1.VMDefinitionR\x02vm\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"v\n" +
	"\x10CreateVMResponse\x12+\n" +
	"\x02vm\x18\x01 \x01(\v2\x1b.apiary.rpc.v1.VMDefinitionR\x02vm\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\"]\n" +
	"\x0fUpdateVMRequest\x12+\n" +
	"\x02vm\x18\x01 \x01(\v2\x1b.apiary.rpc.v1.VMDefinitionR\x02vm\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"v\n" +
	"\x10UpdateVMResponse\x12+\n" +
	"\x02vm\x18\x01 \x01(\v2\x1b.apiary.rpc.v1.VMDefinitionR\x02vm\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\"@\n" +
	"\x0fDeleteVMRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"v\n" +
	"\x10DeleteVMResponse\x12+\n" +
	"\x02vm\x18\x01 \x01(\v2\x1b.apiary.rpc.v1.VMDefinitionR\x02vm\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\"\x1e\n" +
	"\fGetVMRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x89\x01\n" +
	"\rGetVMResponse\x12+\n" +
	"\x02vm\x18\x01 \x01(\v2\x1b.apiary.rpc.v1.VMDefinitionR\x02vm\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vleader_hint\x18\x04 \x01(\tR\n" +
	"leaderHint\"\x10\n" +
	"\x0eListVMsRequest\"w\n" +
	"\x0fListVMsResponse\x12-\n" +
	"\x03vms\x18\x01 \x03(\v2\x1b.apiary.rpc.v1.VMDefinitionR\x03vms\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\"\x0f\n" +
	"\rStatusRequest\"\x8e\x03\n" +
	"\x0eStatusResponse\x12&\n" +
	"\x0fmanager_node_id\x18\x01 \x01(\tR\rmanagerNodeId\x12%\n" +
	"\x0eraft_reachable\x18\x02 \x01(\bR\rraftReachable\x12\x1d\n" +
	"\n" +
	"raft_error\x18\x03 \x01(\tR\traftError\x12$\n" +
	"\x0eraft_is_leader\x18\x04 \x01(\bR\fraftIsLeader\x12$\n" +
	"\x0eraft_leader_id\x18\x05 \x01(\tR\fraftLeaderId\x12 \n" +
	"\fraft_node_id\x18\x06 \x01(\tR\n" +
	"raftNodeId\x12-\n" +
	"\x13raft_last_log_index\x18\a \x01(\x04R\x10raftLastLogIndex\x12,\n" +
	"\x12raft_applied_index\x18\b \x01(\x04R\x10raftAppliedIndex\x12\x1d\n" +
	"\n" +
	"raft_state\x18\t \x01(\tR\traftState\x12$\n" +
	"\x0eknown_node_ids\x18\n" +
	" \x03(\tR\fknownNodeIds\"r\n" +
	"\x10UploadISORequest\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2 .apiary.rpc.v1.ISOUploadMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"P\n" +
	"\x11ISOUploadMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fexpected_sha256\x18\x02 \x01(\tR\x0eexpectedSha256\"t\n" +
	"\x11UploadISOResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x11\n" +
	"\x0fListISOsRequest\"T\n" +
	"\aISOInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"T\n" +
	"\x10ListISOsResponse\x12*\n" +
	"\x04isos\x18\x01 \x03(\v2\x16.apiary.rpc.v1.ISOInfoR\x04isos\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x10DeleteISORequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x11DeleteISOResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x12\n" +
	"\x10HostStatsRequest\"|\n" +
	"\bCPUStats\x12\x14\n" +
	"\x05cores\x18\x01 \x01(\x05R\x05cores\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\x02 \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\x03 \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\x04 \x01(\x01R\tloadAvg15\"J\n" +
	"\bMemStats\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x02 \x01(\x04R\tfreeBytes\"\xb9\x01\n" +
	"\tPoolStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x1f\n" +
	"\valloc_bytes\x18\x03 \x01(\x04R\n" +
	"allocBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x04 \x01(\x04R\tfreeBytes\x12!\n" +
	"\fcapacity_pct\x18\x05 \x01(\rR\vcapacityPct\x12\x16\n" +
	"\x06health\x18\x06 \x01(\tR\x06health\"}\n" +
	"\tDiskStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"Y\n" +
	"\rNetIfaceStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\"\xaa\x02\n" +
	"\x11HostStatsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x03cpu\x18\x02 \x01(\v2\x17.apiary.rpc.v1.CPUStatsR\x03cpu\x12)\n" +
	"\x03mem\x18\x03 \x01(\v2\x17.apiary.rpc.v1.MemStatsR\x03mem\x12.\n" +
	"\x05pools\x18\x04 \x03(\v2\x18.apiary.rpc.v1.PoolStatsR\x05pools\x12.\n" +
	"\x05disks\x18\x05 \x03(\v2\x18.apiary.rpc.v1.DiskStatsR\x05disks\x12.\n" +
	"\x03net\x18\x06 \x03(\v2\x1c.apiary.rpc.v1.NetIfaceStatsR\x03net\x12\x16\n" +
	"\x06errors\x18\a \x03(\tR\x06errors\"%\n" +
	"\x13GetVMConsoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"r\n" +
	"\x14GetVMConsoleResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*f\n" +
	"\aVMState\x12\x18\n" +
	"\x14VM_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VM_STATE_STOPPED\x10\x01\x12\x14\n" +
	"\x10VM_STATE_RUNNING\x10\x02\x12\x15\n" +
	"\x11VM_STATE_DELETING\x10\x03*y\n" +
	"\aVMPhase\x12\x18\n" +
	"\x14VM_PHASE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VM_PHASE_CREATING\x10\x01\x12\x12\n" +
	"\x0eVM_PHASE_READY\x10\x02\x12\x15\n" +
	"\x11VM_PHASE_DELETING\x10\x03\x12\x12\n" +
	"\x0eVM_PHASE_ERROR\x10\x042\xe4\x06\n" +
	"\x0eManagerService\x12E\n" +
	"\x06Status\x12\x1c.apiary.rpc.v1.StatusRequest\x1a\x1d.apiary.rpc.v1.StatusResponse\x12K\n" +
	"\bCreateVM\x12\x1e.apiary.rpc.v1.CreateVMRequest\x1a\x1f.apiary.rpc.v1.CreateVMResponse\x12K\n" +
	"\bUpdateVM\x12\x1e.apiary.rpc.v1.UpdateVMRequest\x1a\x1f.apiary.rpc.v1.UpdateVMResponse\x12K\n" +
	"\bDeleteVM\x12\x1e.apiary.rpc.v1.DeleteVMRequest\x1a\x1f.apiary.rpc.v1.DeleteVMResponse\x12B\n" +
	"\x05GetVM\x12\x1b.apiary.rpc.v1.GetVMRequest\x1a\x1c.apiary.rpc.v1.GetVMResponse\x12H\n" +
	"\aListVMs\x12\x1d.apiary.rpc.v1.ListVMsRequest\x1a\x1e.apiary.rpc.v1.ListVMsResponse\x12P\n" +
	"\tUploadISO\x12\x1f.apiary.rpc.v1.UploadISORequest\x1a .apiary.rpc.v1.UploadISOResponse(\x01\x12K\n" +
	"\bListISOs\x12\x1e.apiary.rpc.v1.ListISOsRequest\x1a\x1f.apiary.rpc.v1.ListISOsResponse\x12N\n" +
	"\tDeleteISO\x12\x1f.apiary.rpc.v1.DeleteISORequest\x1a .apiary.rpc.v1.DeleteISOResponse\x12N\n" +
	"\tHostStats\x12\x1f.apiary.rpc.v1.HostStatsRequest\x1a .apiary.rpc.v1.HostStatsResponse\x12W\n" +
	"\fGetVMConsole\x12\".apiary.rpc.v1.GetVMConsoleRequest\x1a#.apiary.rpc.v1.GetVMConsoleResponseB-Z+github.com/glenjbarber/apiary/api/rpc;rpcpbb\x06proto3"

var (
	file_api_rpc_manager_proto_rawDescOnce sync.Once
	file_api_rpc_manager_proto_rawDescData []byte
)

func file_api_rpc_manager_proto_rawDescGZIP() []byte {
	file_api_rpc_manager_proto_rawDescOnce.Do(func() {
		file_api_rpc_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rpc_manager_proto_rawDesc), len(file_api_rpc_manager_proto_rawDesc)))
	})
	return file_api_rpc_manager_proto_rawDescData
}

var file_api_rpc_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_rpc_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_rpc_manager_proto_goTypes = []any{
	(VMState)(0),                 // 0: apiary.rpc.v1.VMState
	(VMPhase)(0),                 // 1: apiary.rpc.v1.VMPhase
	(*VMDefinition)(nil),         // 2: apiary.rpc.v1.VMDefinition
	(*CreateVMRequest)(nil),      // 3: apiary.rpc.v1.CreateVMRequest
	(*CreateVMResponse)(nil),     // 4: apiary.rpc.v1.CreateVMResponse
	(*UpdateVMRequest)(nil),      // 5: apiary.rpc.v1.UpdateVMRequest
	(*UpdateVMResponse)(nil),     // 6: apiary.rpc.v1.UpdateVMResponse
	(*DeleteVMRequest)(nil),      // 7: apiary.rpc.v1.DeleteVMRequest
	(*DeleteVMResponse)(nil),     // 8: apiary.rpc.v1.DeleteVMResponse
	(*GetVMRequest)(nil),         // 9: apiary.rpc.v1.GetVMRequest
	(*GetVMResponse)(nil),        // 10: apiary.rpc.v1.GetVMResponse
	(*ListVMsRequest)(nil),       // 11: apiary.rpc.v1.ListVMsRequest
	(*ListVMsResponse)(nil),      // 12: apiary.rpc.v1.ListVMsResponse
	(*StatusRequest)(nil),        // 13: apiary.rpc.v1.StatusRequest
	(*StatusResponse)(nil),       // 14: apiary.rpc.v1.StatusResponse
	(*UploadISORequest)(nil),     // 15: apiary.rpc.v1.UploadISORequest
	(*ISOUploadMetadata)(nil),    // 16: apiary.rpc.v1.ISOUploadMetadata
	(*UploadISOResponse)(nil),    // 17: apiary.rpc.v1.UploadISOResponse
	(*ListISOsRequest)(nil),      // 18: apiary.rpc.v1.ListISOsRequest
	(*ISOInfo)(nil),              // 19: apiary.rpc.v1.ISOInfo
	(*ListISOsResponse)(nil),     // 20: apiary.rpc.v1.ListISOsResponse
	(*DeleteISORequest)(nil),     // 21: apiary.rpc.v1.DeleteISORequest
	(*DeleteISOResponse)(nil),    // 22: apiary.rpc.v1.DeleteISOResponse
	(*HostStatsRequest)(nil),     // 23: apiary.rpc.v1.HostStatsRequest
	(*CPUStats)(nil),             // 24: apiary.rpc.v1.CPUStats
	(*MemStats)(nil),             // 25: apiary.rpc.v1.MemStats
	(*PoolStats)(nil),            // 26: apiary.rpc.v1.PoolStats
	(*DiskStats)(nil),            // 27: apiary.rpc.v1.DiskStats
	(*NetIfaceStats)(nil),        // 28: apiary.rpc.v1.NetIfaceStats
	(*HostStatsResponse)(nil),    // 29: apiary.rpc.v1.HostStatsResponse
	(*GetVMConsoleRequest)(nil),  // 30: apiary.rpc.v1.GetVMConsoleRequest
	(*GetVMConsoleResponse)(nil), // 31: apiary.rpc.v1.GetVMConsoleResponse
}
var file_api_rpc_manager_proto_depIdxs = []int32{
	0,  // 0: apiary.rpc.v1.VMDefinition.desired_state:type_name -> apiary.rpc.v1.VMState
	1,  // 1: apiary.rpc.v1.VMDefinition.phase:type_name -> apiary.rpc.v1.VMPhase
	2,  // 2: apiary.rpc.v1.CreateVMRequest.vm:type_name -> apiary.rpc.v1.VMDefinition
	2,  // 3: apiary.rpc.v1.CreateVMResponse.vm:type_name -> apiary.rpc.v1.VMDefinition
	2,  // 4: apiary.rpc.v1.UpdateVMRequest.vm:type_name -> apiary.rpc.v1.VMDefinition
	2,  // 5: apiary.rpc.v1.UpdateVMResponse.vm:type_name -> apiary.rpc.v1.VMDefinition
	2,  // 6: apiary.rpc.v1.DeleteVMResponse.vm:type_name -> apiary.rpc.v1.VMDefinition
	2,  // 7: apiary.rpc.v1.GetVMResponse.vm:type_name -> apiary.rpc.v1.VMDefinition
	2,  // 8: apiary.rpc.v1.ListVMsResponse.vms:type_name -> apiary.rpc.v1.VMDefinition
	16, // 9: apiary.rpc.v1.UploadISORequest.metadata:type_name -> apiary.rpc.v1.ISOUploadMetadata
	19, // 10: apiary.rpc.v1.ListISOsResponse.isos:type_name -> apiary.rpc.v1.ISOInfo
	24, // 11: apiary.rpc.v1.HostStatsResponse.cpu:type_name -> apiary.rpc.v1.CPUStats
	25, // 12: apiary.rpc.v1.HostStatsResponse.mem:type_name -> apiary.rpc.v1.MemStats
	26, // 13: apiary.rpc.v1.HostStatsResponse.pools:type_name -> apiary.rpc.v1.PoolStats
	27, // 14: apiary.rpc.v1.HostStatsResponse.disks:type_name -> apiary.rpc.v1.DiskStats
	28, // 15: apiary.rpc.v1.HostStatsResponse.net:type_name -> apiary.rpc.v1.NetIfaceStats
	13, // 16: apiary.rpc.v1.ManagerService.Status:input_type -> apiary.rpc.v1.StatusRequest
	3,  // 17: apiary.rpc.v1.ManagerService.CreateVM:input_type -> apiary.rpc.v1.CreateVMRequest
	5,  // 18: apiary.rpc.v1.ManagerService.UpdateVM:input_type -> apiary.rpc.v1.UpdateVMRequest
	7,  // 19: apiary.rpc.v1.ManagerService.DeleteVM:input_type -> apiary.rpc.v1.DeleteVMRequest
	9,  // 20: apiary.rpc.v1.ManagerService.GetVM:input_type -> apiary.rpc.v1.GetVMRequest
	11, // 21: apiary.rpc.v1.ManagerService.ListVMs:input_type -> apiary.rpc.v1.ListVMsRequest
	15, // 22: apiary.rpc.v1.ManagerService.UploadISO:input_type -> apiary.rpc.v1.UploadISORequest
	18, // 23: apiary.rpc.v1.ManagerService.ListISOs:input_type -> apiary.rpc.v1.ListISOsRequest
	21, // 24: apiary.rpc.v1.ManagerService.DeleteISO:input_type -> apiary.rpc.v1.DeleteISORequest
	23, // 25: apiary.rpc.v1.ManagerService.HostStats:input_type -> apiary.rpc.v1.HostStatsRequest
	30, // 26: apiary.rpc.v1.ManagerService.GetVMConsole:input_type -> apiary.rpc.v1.GetVMConsoleRequest
	14, // 27: apiary.rpc.v1.ManagerService.Status:output_type -> apiary.rpc.v1.StatusResponse
	4,  // 28: apiary.rpc.v1.ManagerService.CreateVM:output_type -> apiary.rpc.v1.CreateVMResponse
	6,  // 29: apiary.rpc.v1.ManagerService.UpdateVM:output_type -> apiary.rpc.v1.UpdateVMResponse
	8,  // 30: apiary.rpc.v1.ManagerService.DeleteVM:output_type -> apiary.rpc.v1.DeleteVMResponse
	10, // 31: apiary.rpc.v1.ManagerService.GetVM:output_type -> apiary.rpc.v1.GetVMResponse
	12, // 32: apiary.rpc.v1.ManagerService.ListVMs:output_type -> apiary.rpc.v1.ListVMsResponse
	17, // 33: apiary.rpc.v1.ManagerService.UploadISO:output_type -> apiary.rpc.v1.UploadISOResponse
	20, // 34: apiary.rpc.v1.ManagerService.ListISOs:output_type -> apiary.rpc.v1.ListISOsResponse
	22, // 35: apiary.rpc.v1.ManagerService.DeleteISO:output_type -> apiary.rpc.v1.DeleteISOResponse
	29, // 36: apiary.rpc.v1.ManagerService.HostStats:output_type -> apiary.rpc.v1.HostStatsResponse
	31, // 37: apiary.rpc.v1.ManagerService.GetVMConsole:output_type -> apiary.rpc.v1.GetVMConsoleResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_rpc_manager_proto_init() }
func file_api_rpc_manager_proto_init() {
	if File_api_rpc_manager_proto != nil {
		return
	}
	file_api_rpc_manager_proto_msgTypes[13].OneofWrappers = []any{
		(*UploadISORequest_Metadata)(nil),
		(*UploadISORequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rpc_manager_proto_rawDesc), len(file_api_rpc_manager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rpc_manager_proto_goTypes,
		DependencyIndexes: file_api_rpc_manager_proto_depIdxs,
		EnumInfos:         file_api_rpc_manager_proto_enumTypes,
		MessageInfos:      file_api_rpc_manager_proto_msgTypes,
	}.Build()
	File_api_rpc_manager_proto = out.File
	file_api_rpc_manager_proto_goTypes = nil
	file_api_rpc_manager_proto_depIdxs = nil
}
