// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/internalpb/raftd.proto

package internalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftInternal_Apply_FullMethodName              = "/apiary.internal.v1.RaftInternal/Apply"
	RaftInternal_Status_FullMethodName             = "/apiary.internal.v1.RaftInternal/Status"
	RaftInternal_AddVoter_FullMethodName           = "/apiary.internal.v1.RaftInternal/AddVoter"
	RaftInternal_RemoveServer_FullMethodName       = "/apiary.internal.v1.RaftInternal/RemoveServer"
	RaftInternal_GetVM_FullMethodName              = "/apiary.internal.v1.RaftInternal/GetVM"
	RaftInternal_ListVMs_FullMethodName            = "/apiary.internal.v1.RaftInternal/ListVMs"
	RaftInternal_GetNetwork_FullMethodName         = "/apiary.internal.v1.RaftInternal/GetNetwork"
	RaftInternal_ListNetworks_FullMethodName       = "/apiary.internal.v1.RaftInternal/ListNetworks"
	RaftInternal_ListVMsLocal_FullMethodName       = "/apiary.internal.v1.RaftInternal/ListVMsLocal"
	RaftInternal_ListNetworksLocal_FullMethodName  = "/apiary.internal.v1.RaftInternal/ListNetworksLocal"
	RaftInternal_ValidateAPIKeyHash_FullMethodName = "/apiary.internal.v1.RaftInternal/ValidateAPIKeyHash"
	RaftInternal_ListAPIKeys_FullMethodName        = "/apiary.internal.v1.RaftInternal/ListAPIKeys"
	RaftInternal_GetJail_FullMethodName            = "/apiary.internal.v1.RaftInternal/GetJail"
	RaftInternal_ListJails_FullMethodName          = "/apiary.internal.v1.RaftInternal/ListJails"
	RaftInternal_ListJailsLocal_FullMethodName     = "/apiary.internal.v1.RaftInternal/ListJailsLocal"
)

// RaftInternalClient is the client API for RaftInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RaftInternal is the internal protocol spoken over the Unix domain socket
// between managerd and raftd. Apply carries an opaque, FSM-defined payload
// rather than a typed ephemeral-state schema, since the real ephemeral
// state types (VM defs, node ownership) haven't been designed yet.
type RaftInternalClient interface {
	// Apply submits a command to the raft log. It only succeeds against the
	// current leader; a non-leader node returns an error and, if known, a
	// hint pointing at the current leader.
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	// Status reports this node's current raft state.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// AddVoter adds a new voting server to the cluster. It only succeeds
	// against the current leader. The new server must already be running
	// and reachable at address before this is called.
	AddVoter(ctx context.Context, in *AddVoterRequest, opts ...grpc.CallOption) (*AddVoterResponse, error)
	// RemoveServer removes a server (voter or otherwise) from the cluster.
	// It only succeeds against the current leader.
	RemoveServer(ctx context.Context, in *RemoveServerRequest, opts ...grpc.CallOption) (*RemoveServerResponse, error)
	// GetVM reads a single VM definition from this node's FSM state. Like
	// Apply, it only succeeds against the current leader - v1's read
	// consistency model is deliberately the same as its write model: the
	// leader is the sole source of truth, avoiding the complexity of
	// serving reads from potentially-lagging followers.
	GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error)
	// ListVMs reads all VM definitions from this node's FSM state, subject
	// to the same leader-only requirement as GetVM.
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	// GetNetwork/ListNetworks mirror GetVM/ListVMs exactly, for
	// NetworkDefinitions instead of VMDefinitions - same leader-only read
	// model, same reasoning. CreateNetwork/DeleteNetwork need no dedicated
	// RPC: they're submitted as Command variants through the existing
	// Apply, exactly like CreateVM/DeleteVM already are.
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	// ListVMsLocal/ListNetworksLocal read the same state as ListVMs/
	// ListNetworks above, but deliberately WITHOUT the leader-only
	// restriction - see ValidateAPIKeyHash's doc comment below for the
	// exact same reasoning, applied here for the first time to plain
	// reads rather than auth. internal/cluster's Reconciler runs
	// identically on every node, leader or follower, deciding what to
	// provision locally (its own VMs, HAST replica roles, network
	// interfaces) - none of that depends on this node being the raft
	// leader, so requiring leadership here would make every non-leader
	// node's reconciler permanently unable to do its job. This was a
	// real, previously-latent gap: found live when a genuine second raft
	// node's Reconciler.RunOnce failed outright with "this node is not
	// the leader" the first time real multi-node reconciliation was
	// exercised (every deployment before this had exactly one node,
	// always the leader, so ListVMs/ListNetworks's leader restriction
	// never actually mattered) - see ADR-0025. ListVMs/ListNetworks
	// themselves stay leader-only, unchanged, for external API reads
	// (GetVM/ListVMs on ManagerService) - only the reconciler's own
	// internal use is affected.
	ListVMsLocal(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	ListNetworksLocal(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	// ValidateAPIKeyHash checks a hashed API key against this node's own
	// FSM state (ADR-0023) - deliberately NOT leader-only, unlike every
	// other read RPC in this service. Raft already replicates FSM state
	// (including api_keys) onto every node, follower or leader, as they
	// replay the log; several managerd RPCs need to keep authenticating
	// callers even on a non-leader node (HostStats, GetVMConsole,
	// UploadISO are all local, per-node operations that don't otherwise
	// depend on raft leadership at all), so this can't require the
	// leader the way GetNetwork/ListNetworks do. hashed_key may be
	// empty - a caller checking only auth_enabled (used by managerd's
	// "auth never turned on yet = fully open" bootstrap check).
	ValidateAPIKeyHash(ctx context.Context, in *ValidateAPIKeyHashRequest, opts ...grpc.CallOption) (*ValidateAPIKeyHashResponse, error)
	// ListAPIKeys is a normal leader-only read (mirrors ListNetworks),
	// used only for the admin-facing key list - never for per-request
	// authentication, which goes through ValidateAPIKeyHash instead.
	ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error)
	// GetJail/ListJails mirror GetNetwork/ListNetworks exactly, for
	// jail orchestration (ADR-0026's second half).
	GetJail(ctx context.Context, in *GetJailRequest, opts ...grpc.CallOption) (*GetJailResponse, error)
	ListJails(ctx context.Context, in *ListJailsRequest, opts ...grpc.CallOption) (*ListJailsResponse, error)
	// ListJailsLocal mirrors ListVMsLocal/ListNetworksLocal above -
	// internal/cluster's Reconciler needs to read jail state on every
	// node, leader or not, for the exact same reason it needs
	// ListVMsLocal/ListNetworksLocal.
	ListJailsLocal(ctx context.Context, in *ListJailsRequest, opts ...grpc.CallOption) (*ListJailsResponse, error)
}

type raftInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftInternalClient(cc grpc.ClientConnInterface) RaftInternalClient {
	return &raftInternalClient{cc}
}

func (c *raftInternalClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, RaftInternal_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, RaftInternal_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) AddVoter(ctx context.Context, in *AddVoterRequest, opts ...grpc.CallOption) (*AddVoterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVoterResponse)
	err := c.cc.Invoke(ctx, RaftInternal_AddVoter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) RemoveServer(ctx context.Context, in *RemoveServerRequest, opts ...grpc.CallOption) (*RemoveServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveServerResponse)
	err := c.cc.Invoke(ctx, RaftInternal_RemoveServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMResponse)
	err := c.cc.Invoke(ctx, RaftInternal_GetVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, RaftInternal_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkResponse)
	err := c.cc.Invoke(ctx, RaftInternal_GetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, RaftInternal_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) ListVMsLocal(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, RaftInternal_ListVMsLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) ListNetworksLocal(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, RaftInternal_ListNetworksLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) ValidateAPIKeyHash(ctx context.Context, in *ValidateAPIKeyHashRequest, opts ...grpc.CallOption) (*ValidateAPIKeyHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAPIKeyHashResponse)
	err := c.cc.Invoke(ctx, RaftInternal_ValidateAPIKeyHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIKeysResponse)
	err := c.cc.Invoke(ctx, RaftInternal_ListAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) GetJail(ctx context.Context, in *GetJailRequest, opts ...grpc.CallOption) (*GetJailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJailResponse)
	err := c.cc.Invoke(ctx, RaftInternal_GetJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) ListJails(ctx context.Context, in *ListJailsRequest, opts ...grpc.CallOption) (*ListJailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJailsResponse)
	err := c.cc.Invoke(ctx, RaftInternal_ListJails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftInternalClient) ListJailsLocal(ctx context.Context, in *ListJailsRequest, opts ...grpc.CallOption) (*ListJailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJailsResponse)
	err := c.cc.Invoke(ctx, RaftInternal_ListJailsLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftInternalServer is the server API for RaftInternal service.
// All implementations must embed UnimplementedRaftInternalServer
// for forward compatibility.
//
// RaftInternal is the internal protocol spoken over the Unix domain socket
// between managerd and raftd. Apply carries an opaque, FSM-defined payload
// rather than a typed ephemeral-state schema, since the real ephemeral
// state types (VM defs, node ownership) haven't been designed yet.
type RaftInternalServer interface {
	// Apply submits a command to the raft log. It only succeeds against the
	// current leader; a non-leader node returns an error and, if known, a
	// hint pointing at the current leader.
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	// Status reports this node's current raft state.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// AddVoter adds a new voting server to the cluster. It only succeeds
	// against the current leader. The new server must already be running
	// and reachable at address before this is called.
	AddVoter(context.Context, *AddVoterRequest) (*AddVoterResponse, error)
	// RemoveServer removes a server (voter or otherwise) from the cluster.
	// It only succeeds against the current leader.
	RemoveServer(context.Context, *RemoveServerRequest) (*RemoveServerResponse, error)
	// GetVM reads a single VM definition from this node's FSM state. Like
	// Apply, it only succeeds against the current leader - v1's read
	// consistency model is deliberately the same as its write model: the
	// leader is the sole source of truth, avoiding the complexity of
	// serving reads from potentially-lagging followers.
	GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error)
	// ListVMs reads all VM definitions from this node's FSM state, subject
	// to the same leader-only requirement as GetVM.
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	// GetNetwork/ListNetworks mirror GetVM/ListVMs exactly, for
	// NetworkDefinitions instead of VMDefinitions - same leader-only read
	// model, same reasoning. CreateNetwork/DeleteNetwork need no dedicated
	// RPC: they're submitted as Command variants through the existing
	// Apply, exactly like CreateVM/DeleteVM already are.
	GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error)
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	// ListVMsLocal/ListNetworksLocal read the same state as ListVMs/
	// ListNetworks above, but deliberately WITHOUT the leader-only
	// restriction - see ValidateAPIKeyHash's doc comment below for the
	// exact same reasoning, applied here for the first time to plain
	// reads rather than auth. internal/cluster's Reconciler runs
	// identically on every node, leader or follower, deciding what to
	// provision locally (its own VMs, HAST replica roles, network
	// interfaces) - none of that depends on this node being the raft
	// leader, so requiring leadership here would make every non-leader
	// node's reconciler permanently unable to do its job. This was a
	// real, previously-latent gap: found live when a genuine second raft
	// node's Reconciler.RunOnce failed outright with "this node is not
	// the leader" the first time real multi-node reconciliation was
	// exercised (every deployment before this had exactly one node,
	// always the leader, so ListVMs/ListNetworks's leader restriction
	// never actually mattered) - see ADR-0025. ListVMs/ListNetworks
	// themselves stay leader-only, unchanged, for external API reads
	// (GetVM/ListVMs on ManagerService) - only the reconciler's own
	// internal use is affected.
	ListVMsLocal(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	ListNetworksLocal(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	// ValidateAPIKeyHash checks a hashed API key against this node's own
	// FSM state (ADR-0023) - deliberately NOT leader-only, unlike every
	// other read RPC in this service. Raft already replicates FSM state
	// (including api_keys) onto every node, follower or leader, as they
	// replay the log; several managerd RPCs need to keep authenticating
	// callers even on a non-leader node (HostStats, GetVMConsole,
	// UploadISO are all local, per-node operations that don't otherwise
	// depend on raft leadership at all), so this can't require the
	// leader the way GetNetwork/ListNetworks do. hashed_key may be
	// empty - a caller checking only auth_enabled (used by managerd's
	// "auth never turned on yet = fully open" bootstrap check).
	ValidateAPIKeyHash(context.Context, *ValidateAPIKeyHashRequest) (*ValidateAPIKeyHashResponse, error)
	// ListAPIKeys is a normal leader-only read (mirrors ListNetworks),
	// used only for the admin-facing key list - never for per-request
	// authentication, which goes through ValidateAPIKeyHash instead.
	ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error)
	// GetJail/ListJails mirror GetNetwork/ListNetworks exactly, for
	// jail orchestration (ADR-0026's second half).
	GetJail(context.Context, *GetJailRequest) (*GetJailResponse, error)
	ListJails(context.Context, *ListJailsRequest) (*ListJailsResponse, error)
	// ListJailsLocal mirrors ListVMsLocal/ListNetworksLocal above -
	// internal/cluster's Reconciler needs to read jail state on every
	// node, leader or not, for the exact same reason it needs
	// ListVMsLocal/ListNetworksLocal.
	ListJailsLocal(context.Context, *ListJailsRequest) (*ListJailsResponse, error)
	mustEmbedUnimplementedRaftInternalServer()
}

// UnimplementedRaftInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftInternalServer struct{}

func (UnimplementedRaftInternalServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedRaftInternalServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedRaftInternalServer) AddVoter(context.Context, *AddVoterRequest) (*AddVoterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVoter not implemented")
}
func (UnimplementedRaftInternalServer) RemoveServer(context.Context, *RemoveServerRequest) (*RemoveServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveServer not implemented")
}
func (UnimplementedRaftInternalServer) GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVM not implemented")
}
func (UnimplementedRaftInternalServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedRaftInternalServer) GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetwork not implemented")
}
func (UnimplementedRaftInternalServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedRaftInternalServer) ListVMsLocal(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMsLocal not implemented")
}
func (UnimplementedRaftInternalServer) ListNetworksLocal(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworksLocal not implemented")
}
func (UnimplementedRaftInternalServer) ValidateAPIKeyHash(context.Context, *ValidateAPIKeyHashRequest) (*ValidateAPIKeyHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAPIKeyHash not implemented")
}
func (UnimplementedRaftInternalServer) ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAPIKeys not implemented")
}
func (UnimplementedRaftInternalServer) GetJail(context.Context, *GetJailRequest) (*GetJailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJail not implemented")
}
func (UnimplementedRaftInternalServer) ListJails(context.Context, *ListJailsRequest) (*ListJailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJails not implemented")
}
func (UnimplementedRaftInternalServer) ListJailsLocal(context.Context, *ListJailsRequest) (*ListJailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJailsLocal not implemented")
}
func (UnimplementedRaftInternalServer) mustEmbedUnimplementedRaftInternalServer() {}
func (UnimplementedRaftInternalServer) testEmbeddedByValue()                      {}

// UnsafeRaftInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftInternalServer will
// result in compilation errors.
type UnsafeRaftInternalServer interface {
	mustEmbedUnimplementedRaftInternalServer()
}

func RegisterRaftInternalServer(s grpc.ServiceRegistrar, srv RaftInternalServer) {
	// If the following call panics, it indicates UnimplementedRaftInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftInternal_ServiceDesc, srv)
}

func _RaftInternal_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_AddVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).AddVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_AddVoter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).AddVoter(ctx, req.(*AddVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_RemoveServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).RemoveServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_RemoveServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).RemoveServer(ctx, req.(*RemoveServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_GetVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).GetVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_GetVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).GetVM(ctx, req.(*GetVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_GetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_ListVMsLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).ListVMsLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_ListVMsLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).ListVMsLocal(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_ListNetworksLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).ListNetworksLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_ListNetworksLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).ListNetworksLocal(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_ValidateAPIKeyHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAPIKeyHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).ValidateAPIKeyHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_ValidateAPIKeyHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).ValidateAPIKeyHash(ctx, req.(*ValidateAPIKeyHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_ListAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).ListAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_ListAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).ListAPIKeys(ctx, req.(*ListAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_GetJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).GetJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_GetJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).GetJail(ctx, req.(*GetJailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_ListJails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).ListJails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_ListJails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).ListJails(ctx, req.(*ListJailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftInternal_ListJailsLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftInternalServer).ListJailsLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftInternal_ListJailsLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftInternalServer).ListJailsLocal(ctx, req.(*ListJailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftInternal_ServiceDesc is the grpc.ServiceDesc for RaftInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apiary.internal.v1.RaftInternal",
	HandlerType: (*RaftInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _RaftInternal_Apply_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _RaftInternal_Status_Handler,
		},
		{
			MethodName: "AddVoter",
			Handler:    _RaftInternal_AddVoter_Handler,
		},
		{
			MethodName: "RemoveServer",
			Handler:    _RaftInternal_RemoveServer_Handler,
		},
		{
			MethodName: "GetVM",
			Handler:    _RaftInternal_GetVM_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _RaftInternal_ListVMs_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _RaftInternal_GetNetwork_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _RaftInternal_ListNetworks_Handler,
		},
		{
			MethodName: "ListVMsLocal",
			Handler:    _RaftInternal_ListVMsLocal_Handler,
		},
		{
			MethodName: "ListNetworksLocal",
			Handler:    _RaftInternal_ListNetworksLocal_Handler,
		},
		{
			MethodName: "ValidateAPIKeyHash",
			Handler:    _RaftInternal_ValidateAPIKeyHash_Handler,
		},
		{
			MethodName: "ListAPIKeys",
			Handler:    _RaftInternal_ListAPIKeys_Handler,
		},
		{
			MethodName: "GetJail",
			Handler:    _RaftInternal_GetJail_Handler,
		},
		{
			MethodName: "ListJails",
			Handler:    _RaftInternal_ListJails_Handler,
		},
		{
			MethodName: "ListJailsLocal",
			Handler:    _RaftInternal_ListJailsLocal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/internalpb/raftd.proto",
}
