// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/internalpb/raftd.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is an opaque, FSM-defined command. Its encoding is not
	// interpreted by raftd itself.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// timeout_ms bounds how long to wait for the command to be committed and
	// applied. A value of 0 selects raftd's default timeout.
	TimeoutMs     uint32 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_api_internalpb_raftd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_internalpb_raftd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_api_internalpb_raftd_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApplyRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ApplyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is the opaque value returned by the FSM's Apply method.
	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// error is set (non-empty) if the apply failed, including when this node
	// is not the current leader.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// leader_hint is a best-effort address of the current leader, populated
	// when error indicates this node is not the leader.
	LeaderHint    string `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_api_internalpb_raftd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_internalpb_raftd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_api_internalpb_raftd_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ApplyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_internalpb_raftd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_internalpb_raftd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_internalpb_raftd_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	IsLeader     bool                   `protobuf:"varint,1,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId     string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	NodeId       string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LastLogIndex uint64                 `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	AppliedIndex uint64                 `protobuf:"varint,5,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	// raft_state is one of "Leader", "Follower", "Candidate", or "Shutdown".
	RaftState     string `protobuf:"bytes,6,opt,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_internalpb_raftd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_internalpb_raftd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_internalpb_raftd_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *StatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *StatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusResponse) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *StatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetRaftState() string {
	if x != nil {
		return x.RaftState
	}
	return ""
}

var File_api_internalpb_raftd_proto protoreflect.FileDescriptor

const file_api_internalpb_raftd_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/internalpb/raftd.proto\x12\x12apiary.internal.v1\"G\n" +
	"\fApplyRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"^\n" +
	"\rApplyResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\"\x0f\n" +
	"\rStatusRequest\"\xcd\x01\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tis_leader\x18\x01 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12$\n" +
	"\x0elast_log_index\x18\x04 \x01(\x04R\flastLogIndex\x12#\n" +
	"\rapplied_index\x18\x05 \x01(\x04R\fappliedIndex\x12\x1d\n" +
	"\n" +
	"raft_state\x18\x06 \x01(\tR\traftState2\xad\x01\n" +
	"\fRaftInternal\x12L\n" +
	"\x05Apply\x12 .apiary.internal.v1.ApplyRequest\x1a!.apiary.internal.v1.ApplyResponse\x12O\n" +
	"\x06Status\x12!.apiary.internal.v1.StatusRequest\x1a\".apiary.internal.v1.StatusResponseB9Z7github.com/glenjbarber/apiary/api/internalpb;internalpbb\x06proto3"

var (
	file_api_internalpb_raftd_proto_rawDescOnce sync.Once
	file_api_internalpb_raftd_proto_rawDescData []byte
)

func file_api_internalpb_raftd_proto_rawDescGZIP() []byte {
	file_api_internalpb_raftd_proto_rawDescOnce.Do(func() {
		file_api_internalpb_raftd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_internalpb_raftd_proto_rawDesc), len(file_api_internalpb_raftd_proto_rawDesc)))
	})
	return file_api_internalpb_raftd_proto_rawDescData
}

var file_api_internalpb_raftd_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_internalpb_raftd_proto_goTypes = []any{
	(*ApplyRequest)(nil),   // 0: apiary.internal.v1.ApplyRequest
	(*ApplyResponse)(nil),  // 1: apiary.internal.v1.ApplyResponse
	(*StatusRequest)(nil),  // 2: apiary.internal.v1.StatusRequest
	(*StatusResponse)(nil), // 3: apiary.internal.v1.StatusResponse
}
var file_api_internalpb_raftd_proto_depIdxs = []int32{
	0, // 0: apiary.internal.v1.RaftInternal.Apply:input_type -> apiary.internal.v1.ApplyRequest
	2, // 1: apiary.internal.v1.RaftInternal.Status:input_type -> apiary.internal.v1.StatusRequest
	1, // 2: apiary.internal.v1.RaftInternal.Apply:output_type -> apiary.internal.v1.ApplyResponse
	3, // 3: apiary.internal.v1.RaftInternal.Status:output_type -> apiary.internal.v1.StatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_internalpb_raftd_proto_init() }
func file_api_internalpb_raftd_proto_init() {
	if File_api_internalpb_raftd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_internalpb_raftd_proto_rawDesc), len(file_api_internalpb_raftd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_internalpb_raftd_proto_goTypes,
		DependencyIndexes: file_api_internalpb_raftd_proto_depIdxs,
		MessageInfos:      file_api_internalpb_raftd_proto_msgTypes,
	}.Build()
	File_api_internalpb_raftd_proto = out.File
	file_api_internalpb_raftd_proto_goTypes = nil
	file_api_internalpb_raftd_proto_depIdxs = nil
}
